using Microsoft.AspNetCore.Builder;

namespace MintPlayer.Spark.Authorization.Extensions;

public static class SparkAntiforgeryExtensions
{
    /// <summary>
    /// Adds XSRF/CSRF protection for Spark cookie authentication.
    /// Validates the X-XSRF-TOKEN header on mutation endpoints.
    /// Note: The XSRF-TOKEN cookie is now generated by <c>UseSpark()</c> in the core package.
    /// Call this after <c>UseAuthorization()</c> and before <c>UseSpark()</c>.
    /// </summary>
    public static IApplicationBuilder UseSparkAntiforgery(this IApplicationBuilder app)
    {
        app.UseAntiforgery();
        return app;
    }
}
