using System.Security.Cryptography;
using System.Text;

namespace MintPlayer.Spark.IdentityProvider.Services;

/// <summary>
/// Maps a bearer value (authorization code, refresh token) to the id of the document
/// that records it.
/// <para>
/// The id <em>is</em> the SHA-256 of the value, which buys two things that the previous
/// design — storing the raw value in a <c>ReferenceId</c> field and finding it through a
/// static index — did not:
/// </para>
/// <list type="number">
/// <item>
/// <b>Lookups become strongly consistent.</b> RavenDB index queries are eventually
/// consistent, so a code redeemed moments earlier could still be returned as
/// <c>Status == "valid"</c> until the index caught up — replaying a single-use code inside
/// that window. A point-load by id has no such window.
/// </item>
/// <item>
/// <b>A database leak yields no usable credentials.</b> Only the hash is persisted, so a
/// dump of the token collection cannot be replayed against the token endpoint.
/// </item>
/// </list>
/// <para>
/// The value is high-entropy and generated by us, so a plain SHA-256 is sufficient here —
/// unlike a client secret (see <see cref="ClientSecretHasher"/>), which may be operator-chosen
/// and therefore needs a salt and a work factor. Uniqueness also holds by construction: two
/// distinct values cannot claim the same document.
/// </para>
/// </summary>
public static class OidcTokenReference
{
    private const string CollectionPrefix = "OidcTokens/";

    /// <summary>The document id recording <paramref name="value"/>.</summary>
    public static string DocumentId(string value)
    {
        ArgumentException.ThrowIfNullOrEmpty(value);
        return CollectionPrefix + Hash(value);
    }

    private static string Hash(string value)
        => Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(value)));

    /// <summary>
    /// A new bearer value: 256 bits of cryptographic randomness, urlsafe. Returned to the
    /// client once; only <see cref="DocumentId"/> of it is ever persisted.
    /// </summary>
    public static string GenerateValue()
        => Convert.ToBase64String(RandomNumberGenerator.GetBytes(32))
            .TrimEnd('=').Replace('+', '-').Replace('/', '_');
}
