using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.Extensions.Hosting;
using MintPlayer.Spark.Abstractions;
using MintPlayer.Spark.IdentityProvider;
using MintPlayer.Spark.IdentityProvider.Extensions;
using MintPlayer.Spark.IdentityProvider.Models;
using MintPlayer.Spark.IdentityProvider.Services;
using MintPlayer.Spark.Services;
using MintPlayer.Spark.Testing;
using Raven.Client.Documents;
using Raven.Client.Documents.Linq;
using PO = MintPlayer.Spark.Abstractions.PersistentObject;
using POA = MintPlayer.Spark.Abstractions.PersistentObjectAttribute;

namespace MintPlayer.Spark.Tests.IdentityProvider;

/// <summary>
/// M12.7 through the route rather than the Actions class.
/// <para>
/// <see cref="OidcApplicationActionsTests"/> calls <c>OnBeforeSaveAsync</c> directly, which proves
/// the rules and nothing about whether anything reaches them. That gap is not hypothetical: writing
/// these tests is what showed that a refusal from an Actions class had no path to the caller at all
/// — it left the endpoint as an unhandled exception, so every message the audit was careful to
/// phrase for an operator arrived as a 500 with no body. An admin screen whose validation cannot
/// speak is not an admin screen.
/// </para>
/// <para>
/// These cases drive the same model an app gets from <see cref="IOidcApplicationContext"/> —
/// generated by the synchronizer, not hand-authored — so a change to the entity that breaks the
/// screens fails here rather than in someone's deployment.
/// </para>
/// </summary>
public class OidcAdminRouteTests : SparkTestDriver
{
    private sealed class AdminContext : SparkContext, IOidcApplicationContext
    {
        public IRavenQueryable<OidcApplication> OidcApplications => Session.Query<OidcApplication>();
        public IRavenQueryable<OidcScope> OidcScopes => Session.Query<OidcScope>();
    }

    private SparkEndpointFactory<AdminContext> _factory = null!;
    private HttpClient _client = null!;
    private string _cookies = null!;
    private string _xsrf = null!;

    public override async Task InitializeAsync()
    {
        await base.InitializeAsync();

        _factory = new SparkEndpointFactory<AdminContext>(
            Store,
            await GenerateModelsAsync(),
            configureSpark: spark =>
            {
                // The provider is here so the success cases can end where they should: not at
                // "a document exists" but at "the protocol endpoint accepts what the screen wrote".
                spark.AddIdentityProvider(options =>
                {
                    options.Issuer = "https://idp.test";
                    options.SigningKeyPath = Path.Combine(
                        Path.GetTempPath(), "spark-oidc-admin-" + Guid.NewGuid().ToString("N") + ".json");
                });
            },
            environment: "Development");

        _client = _factory.CreateClient();
        (_cookies, _xsrf) = await _factory.MintAntiforgeryAsync();
    }

    public override async Task DisposeAsync()
    {
        _client.Dispose();
        await _factory.DisposeAsync();
        await base.DisposeAsync();
    }

    /// <summary>
    /// Produces the entity definitions the same way a consuming app does — boot once, run the
    /// synchronizer over a context carrying the package's collections, and read back what it wrote.
    /// Hand-authoring them here would test the fixture's idea of the model rather than the one
    /// operators will actually get.
    /// </summary>
    private async Task<EntityTypeFile[]> GenerateModelsAsync()
    {
        await using var scratch = new SparkEndpointFactory<AdminContext>(Store, models: []);
        new ModelSynchronizer(scratch.GetService<IHostEnvironment>(), NSubstitute.Substitute.For<IIndexRegistry>())
            .SynchronizeModels(new AdminContext());

        var dir = Path.Combine(
            scratch.GetService<IHostEnvironment>().ContentRootPath, "App_Data", "Model");

        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        return [.. Directory.GetFiles(dir, "*.json")
            .Select(f => JsonSerializer.Deserialize<EntityTypeFile>(File.ReadAllText(f), options)!)];
    }

    private Task<HttpResponseMessage> PostAsync(
        string typeName, Dictionary<string, object?> attributes, bool withAntiforgery = true)
    {
        var request = new HttpRequestMessage(HttpMethod.Post, $"/spark/po/{typeName}")
        {
            Content = JsonContent.Create(new
            {
                PersistentObject = new PO
                {
                    Name = typeName,
                    ObjectTypeId = Guid.Empty,
                    Attributes = [.. attributes.Select(a => new POA { Name = a.Key, Value = a.Value })],
                },
            }),
        };

        request.Headers.Add("Cookie", _cookies);
        if (withAntiforgery)
            request.Headers.Add("X-XSRF-TOKEN", _xsrf);

        return _client.SendAsync(request);
    }

    /// <summary>The message an operator would read, pulled out of the standard errors envelope.</summary>
    private static async Task<string> ErrorMessageAsync(HttpResponseMessage response)
    {
        var body = JsonDocument.Parse(await response.Content.ReadAsStringAsync()).RootElement;
        var errors = body.GetProperty("result").GetProperty("errors");

        return string.Join(" | ", errors.EnumerateArray().Select(e =>
        {
            var message = e.GetProperty("errorMessage");
            // TranslatedString serializes as a per-culture map, or as a bare string.
            return message.ValueKind == JsonValueKind.String
                ? message.GetString()
                : message.EnumerateObject().First().Value.GetString();
        }));
    }

    /// <summary>
    /// A complete application form. Every attribute is present because a rendered form posts every
    /// field — a test that sends only what it cares about is refused by the declarative validator
    /// for missing value types, which would make each case below pass or fail for the wrong reason.
    /// </summary>
    private static Dictionary<string, object?> Application(string clientId, params (string Name, object? Value)[] overrides)
    {
        var form = new Dictionary<string, object?>
        {
            ["ClientId"] = clientId,
            ["DisplayName"] = clientId,
            ["ClientType"] = "confidential",
            ["Enabled"] = true,
            ["Secrets"] = Array.Empty<object>(),
            ["AllowedGrantTypes"] = new[] { "authorization_code" },
            ["MayIntrospectAnyAudience"] = false,
            ["RedirectUris"] = new[] { $"https://{clientId}.test/cb" },
            ["PostLogoutRedirectUris"] = Array.Empty<string>(),
            ["AllowedCorsOrigins"] = Array.Empty<string>(),
            ["AllowedScopes"] = new[] { "openid" },
            ["Claims"] = Array.Empty<object>(),
            ["ConsentType"] = "explicit",
            ["AllowRememberConsent"] = true,
            ["RequirePkce"] = true,
            ["AccessTokenLifetimeMinutes"] = 60,
            ["RefreshTokenLifetimeDays"] = 14,
        };

        foreach (var (name, value) in overrides)
            form[name] = value;

        return form;
    }

    private static Dictionary<string, object?> Scope(string name, params (string Name, object? Value)[] overrides)
    {
        var form = new Dictionary<string, object?>
        {
            ["Name"] = name,
            ["DisplayName"] = name,
            ["ClaimTypes"] = Array.Empty<string>(),
            ["Audiences"] = Array.Empty<string>(),
            ["Required"] = false,
            ["Emphasize"] = false,
            ["ShowInDiscoveryDocument"] = true,
            ["Enabled"] = true,
        };

        foreach (var (key, value) in overrides)
            form[key] = value;

        return form;
    }

    [Fact]
    public async Task Registering_a_client_through_the_route_persists_it()
    {
        var response = await PostAsync("OidcApplication", Application("route-webapp"));

        response.StatusCode.Should().Be(HttpStatusCode.Created);

        await Store.WaitForIndexingAsync();
        using var session = Store.OpenAsyncSession();
        var stored = await session.Query<OidcApplication>()
            .Where(a => a.ClientId == "route-webapp", exact: true)
            .ToListAsync();

        stored.Should().ContainSingle().Which.RedirectUris.Should().ContainSingle()
            .Which.Should().Be("https://route-webapp.test/cb");
    }

    [Fact]
    public async Task A_client_registered_through_the_route_can_obtain_a_token()
    {
        // The claim M12.7 rests on, end to end: an operator fills in the screen and the protocol
        // endpoint honours the result. Every step in between — model generation, the mapper, the
        // Actions hook that hashes the secret — is load-bearing and none of it is asserted directly.
        (await PostAsync("OidcApplication", Application("route-service",
            ("RedirectUris", Array.Empty<string>()),
            ("AllowedScopes", new[] { "api.read" }),
            ("AllowedGrantTypes", new[] { "client_credentials" }),
            ("Secrets", new object[] { new { Hash = "typed-in-the-screen" } }))))
            .StatusCode.Should().Be(HttpStatusCode.Created);

        (await PostAsync("OidcScope", Scope("api.read")))
            .StatusCode.Should().Be(HttpStatusCode.Created);

        // Client lookup rides an eventually-consistent index, so a just-registered application is
        // not usable the instant the screen returns — the same trap the fixture hit when seeding.
        await Store.WaitForIndexingAsync();

        var token = await _client.PostAsync("/connect/token", new FormUrlEncodedContent(
            new Dictionary<string, string>
            {
                ["grant_type"] = "client_credentials",
                ["client_id"] = "route-service",
                ["client_secret"] = "typed-in-the-screen",
                ["scope"] = "api.read",
            }));

        token.StatusCode.Should().Be(HttpStatusCode.OK,
            "the secret the operator typed must authenticate — it is stored hashed, and a client "
            + "that cannot authenticate against its own registration is the failure this milestone exists to prevent");

        var payload = JsonDocument.Parse(await token.Content.ReadAsStringAsync()).RootElement;
        payload.GetProperty("access_token").GetString().Should().NotBeNullOrEmpty();
        payload.GetProperty("scope").GetString().Should().Be("api.read");
    }

    [Fact]
    public async Task The_secret_an_operator_types_is_stored_hashed()
    {
        (await PostAsync("OidcApplication", Application("route-hashing",
            ("Secrets", new object[] { new { Hash = "plaintext-from-the-form" } }))))
            .StatusCode.Should().Be(HttpStatusCode.Created);

        await Store.WaitForIndexingAsync();
        using var session = Store.OpenAsyncSession();
        var app = (await session.Query<OidcApplication>()
            .Where(a => a.ClientId == "route-hashing", exact: true)
            .ToListAsync()).Single();

        app.Secrets.Should().ContainSingle();
        app.Secrets[0].Hash.Should().NotBe("plaintext-from-the-form");
        ClientSecretHasher.Verify("plaintext-from-the-form", app.Secrets[0].Hash).Should().BeTrue();
    }

    [Fact]
    public async Task A_refused_registration_returns_the_reason_rather_than_a_500()
    {
        var response = await PostAsync("OidcApplication", Application("route-bad-uri",
            ("RedirectUris", new[] { "/callback" })));

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        (await ErrorMessageAsync(response)).Should().Contain("absolute",
            "the operator is the only one who can fix this, so the reason has to reach the screen");
    }

    [Fact]
    public async Task An_unsupported_grant_type_is_refused_at_the_route()
    {
        var response = await PostAsync("OidcApplication", Application("route-implicit",
            ("AllowedGrantTypes", new[] { "implicit" })));

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        (await ErrorMessageAsync(response)).Should().Contain("not supported");
    }

    [Fact]
    public async Task A_duplicate_client_id_is_refused_at_the_route()
    {
        (await PostAsync("OidcApplication", Application("route-twin")))
            .StatusCode.Should().Be(HttpStatusCode.Created);

        await Store.WaitForIndexingAsync();

        var second = await PostAsync("OidcApplication", Application("route-twin"));

        second.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        (await ErrorMessageAsync(second)).Should().Contain("already registered",
            "two applications sharing a client id makes impersonation a matter of index ordering");
    }

    [Fact]
    public async Task A_scope_name_with_whitespace_is_refused_at_the_route()
    {
        var response = await PostAsync("OidcScope", Scope("api read"));

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        (await ErrorMessageAsync(response)).Should().Contain("space-delimited");
    }

    [Fact]
    public async Task Registration_requires_an_antiforgery_token()
    {
        // These screens decide who may mint tokens. A registration a cross-site POST can perform
        // is a client-registration endpoint open to any page the operator happens to visit.
        var response = await PostAsync("OidcApplication", Application("route-csrf"), withAntiforgery: false);

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);

        await Store.WaitForIndexingAsync();
        using var session = Store.OpenAsyncSession();
        (await session.Query<OidcApplication>().Where(a => a.ClientId == "route-csrf", exact: true).ToListAsync())
            .Should().BeEmpty("a rejected request must not have written anything");
    }
}
