using System.Net;
using System.Net.Http.Json;
using Microsoft.Extensions.DependencyInjection;
using MintPlayer.Spark.Abstractions;
using MintPlayer.Spark.Abstractions.Authentication;
using MintPlayer.Spark.Abstractions.Interceptors;
using MintPlayer.Spark.Client;
using MintPlayer.Spark.Contributions;
using MintPlayer.Spark.Extensions;
using MintPlayer.Spark.SoftDelete;
using MintPlayer.Spark.Testing;
using MintPlayer.Spark.Tests._Infrastructure;
using Raven.Client.Documents;
using Raven.Client.Documents.Session;

using PO = MintPlayer.Spark.Abstractions.PersistentObject;

namespace MintPlayer.Spark.Tests.Contributions;

/// <summary>
/// Contributions M5a — the runtime against a real host and a real RavenDB, over HTTP: hydration (R2),
/// per-user writes that never touch the target document (R3) or another user's contribution (R4),
/// latest-wins current documents recomputed on withdraw, hide and restore (R5), the concurrency pin,
/// the owner's delete, the rebuild and the startup shape check.
/// </summary>
/// <remarks>
/// The types are generated by the real Contributions generator (<see cref="CoSong.Lyrics"/>): the test
/// project imports <c>spark-contributions.targets</c>. Fixture names start with <c>Co</c>, because the
/// actions resolver matches by simple name across the assembly.
/// </remarks>
public class ContributionsRuntimeTests : SparkTestDriver
{
    private static readonly Guid SongTypeId = Guid.Parse("c0d10000-0000-4000-8000-c0d100000001");
    private static readonly Guid LyricsTypeId = Guid.Parse("c0d10000-0000-4000-8000-c0d100000002");
    private static readonly Guid ContributionTypeId = Guid.Parse("c0d10000-0000-4000-8000-c0d100000003");
    private const string SongId = "CoSongs/1";
    private const string Alice = "users/alice";
    private const string Bob = "users/bob";

    private readonly List<IAsyncDisposable> factories = [];
    private readonly List<IDisposable> clients = [];

    public override async Task DisposeAsync()
    {
        foreach (var client in clients)
            client.Dispose();
        foreach (var factory in factories)
            await factory.DisposeAsync();
        await base.DisposeAsync();
    }

    private sealed record Host(SparkEndpointFactory Factory, SparkClient Client, CoIdentity Identity, CoProbe Probe, CoRace Race);

    private async Task<Host> StartAsync(Action<IServiceCollection>? services = null, bool seedSong = true)
    {
        if (seedSong)
            await SeedAsync(session => session.StoreAsync(new CoSong { Title = "Gangnam Style" }, SongId));

        var identity = new CoIdentity { Id = Alice };
        var probe = new CoProbe();
        var race = new CoRace(Store);
        var factory = new SparkEndpointFactory(
            Store,
            [SongModel(), LyricsModel(), ContributionModel()],
            configureServices: s =>
            {
                s.AddSingleton(identity);
                s.AddSingleton(probe);
                s.AddSingleton(race);
                s.AddScoped<ISparkCurrentUser, CoCurrentUser>();
                services?.Invoke(s);
            },
            configureSpark: spark =>
            {
                spark.AddSoftDelete();
                spark.AddContributions(typeof(CoSong).Assembly);
                spark.AddPersistentObjectInterceptor<CoProbeBefore>();
                spark.AddPersistentObjectInterceptor<CoProbeAfter>();
                spark.AddPersistentObjectInterceptor<CoRaceInterceptor>();
            });
        factories.Add(factory);
        var client = new SparkClient(factory.CreateClient(), ownsClient: true);
        clients.Add(client);
        return new Host(factory, client, identity, probe, race);
    }

    // ---- helpers --------------------------------------------------------------------------------------

    private static async Task<PO> LoadSongAsync(Host host)
        => await host.Client.GetPersistentObjectAsync(SongTypeId, SongId) ?? throw new InvalidOperationException("song not visible");

    private static PersistentObjectAttributeAsDetail Lyrics(PO po) => (PersistentObjectAttributeAsDetail)po["Lyrics"];

    private static PO NewRow(string language, string script, string text, params (string Name, object Value)[] extra) => new()
    {
        Name = "CoLyrics",
        ObjectTypeId = LyricsTypeId,
        Attributes =
        [
            new PersistentObjectAttribute { Name = "Language", DataType = "string", Value = language, IsValueChanged = true },
            new PersistentObjectAttribute { Name = "Script", DataType = "string", Value = script, IsValueChanged = true },
            new PersistentObjectAttribute { Name = "Text", DataType = "string", Value = text, IsValueChanged = true },
            .. extra.Select(e => new PersistentObjectAttribute { Name = e.Name, DataType = "string", Value = e.Value, IsValueChanged = true }),
        ],
    };

    /// <summary>Replaces the song's rows with <paramref name="rows"/> and saves as the current identity.</summary>
    private static async Task<PO> SaveRowsAsync(Host host, Func<List<PO>, List<PO>> edit)
    {
        var po = await LoadSongAsync(host);
        var lyrics = Lyrics(po);
        lyrics.Objects = edit([.. lyrics.Objects ?? []]);
        lyrics.IsValueChanged = true;
        return await host.Client.UpdatePersistentObjectAsync(po);
    }

    private static Task<PO> AddAsync(Host host, string language, string script, string text)
        => SaveRowsAsync(host, rows => [.. rows, NewRow(language, script, text)]);

    private static Task<PO> EditTextAsync(Host host, string key, string text) => SaveRowsAsync(host, rows =>
    {
        var row = rows.Single(r => r.Id == key);
        row["Text"].Value = text;
        row["Text"].IsValueChanged = true;
        return rows;
    });

    private static Task<PO> RemoveAsync(Host host, string key) => SaveRowsAsync(host, rows => [.. rows.Where(r => r.Id != key)]);

    private async Task<T?> ReadAsync<T>(string id) where T : class
    {
        using var session = Store.OpenAsyncSession();
        return await session.LoadAsync<T>(id);
    }

    private async Task<string?> ChangeVectorAsync<T>(string id) where T : class
    {
        using var session = Store.OpenAsyncSession();
        var doc = await session.LoadAsync<T>(id);
        return doc is null ? null : session.Advanced.GetChangeVectorFor(doc);
    }

    private static string ContributionId(string language, string script, string user) => CoSongLyricsContribution.GetId(SongId, language, script, user);
    private static string CurrentId(string language, string script) => CoSongLyricsCurrent.GetId(SongId, language, script);

    private async Task<IReadOnlyList<string>> IdsStartingWithAsync(string prefix)
    {
        using var session = Store.OpenAsyncSession();
        var docs = await session.Advanced.LoadStartingWithAsync<object>(prefix, pageSize: 1024);
        return [.. docs.Select(d => session.Advanced.GetDocumentId(d))];
    }

    private static string TextOf(PO po, string key) => Lyrics(po).Objects!.Single(r => r.Id == key)["Text"].Value?.ToString() ?? "";

    // ---- R2: hydration -------------------------------------------------------------------------------

    [Fact]
    public async Task Loading_a_song_shows_the_current_versions_with_one_request_for_all_of_them()
    {
        var host = await StartAsync();
        await AddAsync(host, "ko", "Kore", "오빤 강남스타일");
        await AddAsync(host, "ko", "Latn", "oppan gangnam style");
        host.Probe.Clear();

        var po = await LoadSongAsync(host);

        Lyrics(po).Objects!.Select(r => r.Id).Should().BeEquivalentTo(["ko/Kore", "ko/Latn"]);
        TextOf(po, "ko/Latn").Should().Be("oppan gangnam style");
        host.Probe.LoadDeltas.Should().NotBeEmpty("the GET materializes the song");
        host.Probe.LoadDeltas.Should().AllSatisfy(delta => delta.Should().Be(1, "all current versions arrive in one lazy prefix request (R2, S-C6)"));
    }

    // ---- R3: the target is never written ---------------------------------------------------------------

    [Fact]
    public async Task Adding_a_version_writes_my_contribution_and_the_current_document_and_never_the_song()
    {
        var host = await StartAsync();
        var songBefore = await ChangeVectorAsync<CoSong>(SongId);

        await AddAsync(host, "en", "Latn", "Oppa is Gangnam style");

        (await ChangeVectorAsync<CoSong>(SongId)).Should().Be(songBefore, "only contributions changed, so the song document is not rewritten (R3)");
        var mine = await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice));
        mine.Should().NotBeNull();
        mine!.ContributorId.Should().Be(Alice);
        mine.Text.Should().Be("Oppa is Gangnam style");
        var current = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        current!.ContributorId.Should().Be(Alice);
        current.ContributionId.Should().Be(ContributionId("en", "Latn", Alice));
        current.Text.Should().Be("Oppa is Gangnam style");
        current.ContributionCount.Should().Be(1);
    }

    [Fact]
    public async Task A_save_that_changes_no_row_writes_nothing()
    {
        var host = await StartAsync();
        await AddAsync(host, "en", "Latn", "same");
        var contribution = await ChangeVectorAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice));
        var current = await ChangeVectorAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));

        var po = await LoadSongAsync(host);
        po["Title"].Value = "Gangnam Style (2012)";
        po["Title"].IsValueChanged = true;
        Lyrics(po).IsValueChanged = true;
        await host.Client.UpdatePersistentObjectAsync(po);

        (await ReadAsync<CoSong>(SongId))!.Title.Should().Be("Gangnam Style (2012)");
        (await ChangeVectorAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice))).Should().Be(contribution);
        (await ChangeVectorAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"))).Should().Be(current);
    }

    // ---- R4: owner-only --------------------------------------------------------------------------------

    [Fact]
    public async Task Editing_someone_elses_version_writes_only_my_own_contribution_and_tampering_changes_nothing()
    {
        var host = await StartAsync();
        await AddAsync(host, "en", "Latn", "alice's text");
        var alicesBefore = await ChangeVectorAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice));

        host.Identity.Id = Bob;
        await SaveRowsAsync(host, rows =>
        {
            var row = rows.Single(r => r.Id == "en/Latn");
            row["Text"].Value = "bob's correction";
            row["Text"].IsValueChanged = true;
            // Tampering: who wrote it, and a forged contributor/user id. None of these is a writable row attribute.
            var tampered = new PO
            {
                Id = row.Id,
                Name = row.Name,
                ObjectTypeId = row.ObjectTypeId,
                Attributes = [.. row.Attributes,
                    new PersistentObjectAttribute { Name = "ContributorId", DataType = "string", Value = Alice, IsValueChanged = true },
                    new PersistentObjectAttribute { Name = "ContributorName", DataType = "string", Value = "Alice", IsValueChanged = true },
                    new PersistentObjectAttribute { Name = "UserId", DataType = "string", Value = Alice, IsValueChanged = true }],
            };
            return [.. rows.Select(r => r.Id == "en/Latn" ? tampered : r)];
        });

        (await ChangeVectorAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice))).Should().Be(alicesBefore, "Alice's contribution is never touched by Bob (R4)");
        (await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice)))!.Text.Should().Be("alice's text");
        var bobs = await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Bob));
        bobs!.ContributorId.Should().Be(Bob, "the contributor is the caller, whatever was posted");
        bobs.Text.Should().Be("bob's correction");
        var current = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        current!.ContributorId.Should().Be(Bob);
        current.ContributionCount.Should().Be(2);
        (await IdsStartingWithAsync(SongId + "/LyricsContributions/")).Should().HaveCount(2);
    }

    // ---- Q3: withdraw ---------------------------------------------------------------------------------

    [Fact]
    public async Task Removing_a_row_withdraws_only_my_contribution_and_the_previous_version_becomes_current()
    {
        var host = await StartAsync();
        await AddAsync(host, "en", "Latn", "alice's text");
        host.Identity.Id = Bob;
        await EditTextAsync(host, "en/Latn", "bob's text");

        var saved = await RemoveAsync(host, "en/Latn");

        var bobs = await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Bob));
        bobs!.IsDeleted.Should().BeTrue("a withdrawal soft-deletes the caller's own contribution");
        bobs.DeletedBy.Should().Be(Bob);
        (await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice)))!.IsDeleted.Should().BeFalse();
        var current = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        current!.ContributorId.Should().Be(Alice, "the latest visible contribution is current again");
        current.Text.Should().Be("alice's text");
        current.ContributionCount.Should().Be(1);
        TextOf(saved, "en/Latn").Should().Be("alice's text", "the save response shows the version that is current now");

        // Removing a row that shows only someone else's version withdraws nothing.
        await RemoveAsync(host, "en/Latn");
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn")))!.ContributorId.Should().Be(Alice);
        (await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice)))!.IsDeleted.Should().BeFalse();
    }

    [Fact]
    public async Task Withdrawing_the_only_version_deletes_the_current_document_and_saving_again_revives_it()
    {
        var host = await StartAsync();
        await AddAsync(host, "en", "Latn", "first");

        await RemoveAsync(host, "en/Latn");
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"))).Should().BeNull("no visible contribution is left");
        Lyrics(await LoadSongAsync(host)).Objects.Should().BeEmpty();

        await AddAsync(host, "en", "Latn", "second");
        var mine = await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice));
        mine!.IsDeleted.Should().BeFalse("the author's own withdrawal is undone by saving the slot again");
        mine.Text.Should().Be("second");
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn")))!.Text.Should().Be("second");
    }

    [Fact]
    public async Task Changing_a_rows_slot_withdraws_the_old_slot_and_adds_the_new_one()
    {
        var host = await StartAsync();
        await AddAsync(host, "und", "Latn", "lyrics");

        await SaveRowsAsync(host, rows =>
        {
            var row = rows.Single(r => r.Id == "und/Latn");
            row["Language"].Value = "ko";
            row["Language"].IsValueChanged = true;
            return rows;
        });

        (await ReadAsync<CoSongLyricsContribution>(ContributionId("und", "Latn", Alice)))!.IsDeleted.Should().BeTrue();
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("und", "Latn"))).Should().BeNull();
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("ko", "Latn")))!.Text.Should().Be("lyrics");
    }

    // ---- validation -----------------------------------------------------------------------------------

    [Fact]
    public async Task Two_rows_on_one_slot_and_an_invalid_slot_value_are_refused_and_write_nothing()
    {
        var host = await StartAsync();

        var duplicate = await Assert.ThrowsAsync<SparkClientException>(() =>
            SaveRowsAsync(host, rows => [.. rows, NewRow("en", "Latn", "a"), NewRow("en", "Latn", "b")]));
        duplicate.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        duplicate.ResponseBody.Should().Contain("share");

        var invalid = await Assert.ThrowsAsync<SparkClientException>(() => AddAsync(host, "en us", "Latn", "a"));
        invalid.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        invalid.ResponseBody.Should().Contain("Language");

        var slash = await Assert.ThrowsAsync<SparkClientException>(() => AddAsync(host, "en/x", "Latn", "a"));
        slash.StatusCode.Should().Be(HttpStatusCode.BadRequest);

        (await IdsStartingWithAsync(SongId + "/")).Should().BeEmpty("a refused save writes no contribution and no current document");
    }

    [Fact]
    public async Task The_apps_validator_refuses_a_row_and_nothing_is_written()
    {
        var host = await StartAsync(s => s.AddSingleton<IContributionValidator<CoLyrics>, CoValidator>());

        var ex = await Assert.ThrowsAsync<SparkClientException>(() => AddAsync(host, "en", "Latn", "forbidden words"));

        ex.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        ex.ResponseBody.Should().Contain("not allowed");
        (await IdsStartingWithAsync(SongId + "/")).Should().BeEmpty();
        await AddAsync(host, "en", "Latn", "fine words");
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn")))!.Text.Should().Be("fine words");
    }

    [Fact]
    public async Task A_satellite_write_guard_refuses_before_anything_is_written()
    {
        var host = await StartAsync(s => s.AddScoped<ISatelliteWriteGuard, CoLockedGuard>());

        var ex = await Assert.ThrowsAsync<SparkClientException>(() => AddAsync(host, "en", "Latn", "x"));

        ex.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        ex.ResponseBody.Should().Contain("locked");
        (await IdsStartingWithAsync(SongId + "/")).Should().BeEmpty();
    }

    // ---- R5: hide and restore -------------------------------------------------------------------------

    [Fact]
    public async Task Hiding_the_current_contribution_makes_the_previous_one_current_and_restoring_brings_it_back()
    {
        var host = await StartAsync();
        await AddAsync(host, "en", "Latn", "alice's text");
        host.Identity.Id = Bob;
        await EditTextAsync(host, "en/Latn", "bob's spam");

        // A moderator hides Bob's contribution: a soft delete through the contribution type's own PO.
        host.Identity.Id = "users/moderator";
        await host.Client.DeletePersistentObjectAsync(ContributionTypeId, ContributionId("en", "Latn", Bob));

        (await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Bob)))!.IsDeleted.Should().BeTrue();
        var current = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        current!.ContributorId.Should().Be(Alice, "the hide recomputes the current in the delete's own commit (R5, no index lag)");
        current.ContributionCount.Should().Be(1);
        TextOf(await LoadSongAsync(host), "en/Latn").Should().Be("alice's text");

        // A moderator's hide is not undone by the author saving the slot again.
        host.Identity.Id = Bob;
        var refused = await Assert.ThrowsAsync<SparkClientException>(() => EditTextAsync(host, "en/Latn", "bob again"));
        refused.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        refused.ResponseBody.Should().Contain("hidden by a moderator");

        host.Identity.Id = "users/moderator";
        var response = await host.Client.SendAsync(HttpMethod.Post, "/spark/po/restore",
            JsonContent.Create(Wire.Typed(ContributionTypeId, id: ContributionId("en", "Latn", Bob))), requiresAntiforgery: true);
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        current = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        current!.ContributorId.Should().Be(Bob, "the restored contribution is the latest again");
        current.ContributionCount.Should().Be(2);
    }

    // ---- S-C4: two contributors racing ---------------------------------------------------------------

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Two_contributors_racing_on_one_slot_lose_nothing(bool slotExists)
    {
        var host = await StartAsync();
        if (slotExists)
            await AddAsync(host, "en", "Latn", "first");
        var songBefore = await ChangeVectorAsync<CoSong>(SongId);

        host.Race.Arm(SongId);
        var ex = await Assert.ThrowsAsync<SparkClientException>(() => slotExists
            ? EditTextAsync(host, "en/Latn", "alice's edit")
            : AddAsync(host, "en", "Latn", "alice's edit"));

        host.Race.Fired.Should().BeTrue("Bob's save must have landed between Alice's read and her write");
        ex.StatusCode.Should().Be(HttpStatusCode.Conflict, "the current document is written with a pinned change vector; the client's conflict flow takes over");
        var current = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        current!.ContributorId.Should().Be(Bob, "Bob's concurrent version survives");
        current.Text.Should().Be("bob's concurrent text");
        var alices = await ReadAsync<CoSongLyricsContribution>(ContributionId("en", "Latn", Alice));
        if (slotExists)
            alices!.Text.Should().Be("first", "the refused save rolled back Alice's contribution with it (one transaction)");
        else
            alices.Should().BeNull("the refused save rolled back Alice's contribution with it (one transaction)");
        (await ChangeVectorAsync<CoSong>(SongId)).Should().Be(songBefore);

        // The retry the client makes after re-fetching succeeds.
        await EditTextAsync(host, "en/Latn", "alice's edit");
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn")))!.ContributorId.Should().Be(Alice);
    }

    // ---- the owner's delete ---------------------------------------------------------------------------

    [Fact]
    public async Task Deleting_the_song_deletes_its_contributions_and_current_documents_in_the_same_commit()
    {
        var host = await StartAsync();
        await SeedAsync(session => session.StoreAsync(new CoSong { Title = "other" }, "CoSongs/10"));
        await AddAsync(host, "en", "Latn", "a");
        host.Identity.Id = Bob;
        await AddAsync(host, "ko", "Kore", "b");
        await RemoveAsync(host, "ko/Kore");

        await host.Client.DeletePersistentObjectAsync(SongTypeId, SongId);

        (await ReadAsync<CoSong>(SongId)).Should().BeNull();
        (await IdsStartingWithAsync(SongId + "/")).Should().BeEmpty("withdrawn and live contributions and every current document go with the song");
        (await ReadAsync<CoSong>("CoSongs/10")).Should().NotBeNull("CoSongs/1 is not a prefix of CoSongs/10");
    }

    // ---- rebuild --------------------------------------------------------------------------------------

    [Fact]
    public async Task RebuildCurrentAsync_repairs_hand_corrupted_current_documents()
    {
        var host = await StartAsync();
        await AddAsync(host, "en", "Latn", "alice's text");
        host.Identity.Id = Bob;
        await EditTextAsync(host, "en/Latn", "bob's text");

        await SeedAsync(async session =>
        {
            var current = await session.LoadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
            current.Text = "corrupted";
            current.ContributorId = "users/nobody";
            await session.StoreAsync(new CoSongLyricsCurrent { TargetId = SongId, Language = "fr", Script = "Latn", Text = "orphan" }, CurrentId("fr", "Latn"));
        });

        using (var scope = host.Factory.CreateScope())
            await scope.ServiceProvider.GetRequiredService<IContributions>().RebuildCurrentAsync(SongId);

        var repaired = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        repaired!.Text.Should().Be("bob's text");
        repaired.ContributorId.Should().Be(Bob);
        repaired.ContributionCount.Should().Be(2);
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("fr", "Latn"))).Should().BeNull("no contribution backs it");
    }

    [Fact]
    public async Task A_changed_shape_rebuilds_every_target_at_startup()
    {
        // State left by an older shape: a contribution, a stale current, and a marker with another hash.
        await SeedAsync(async session =>
        {
            await session.StoreAsync(new CoSong { Title = "t" }, SongId);
            await session.StoreAsync(new CoSongLyricsContribution
            {
                TargetId = SongId, ContributorId = Alice, Language = "en", Script = "Latn", Text = "truth",
                UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
            }, ContributionId("en", "Latn", Alice));
            await session.StoreAsync(new CoSongLyricsCurrent { TargetId = SongId, Language = "en", Script = "Latn", Text = "stale" }, CurrentId("en", "Latn"));
            await session.StoreAsync(new ContributionShapeMarker { Shape = "0000000000000000" }, ContributionShapeMarker.IdFor(CoSongLyricsContributionMetadata.Instance));
        });

        await StartAsync(seedSong: false);

        var current = await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"));
        current!.Text.Should().Be("truth", "the startup check rebuilt the current documents of the changed declaration");
        current.ContributionCount.Should().Be(1);
        current.ContributionId.Should().Be(ContributionId("en", "Latn", Alice));
        (await ReadAsync<ContributionShapeMarker>(ContributionShapeMarker.IdFor(CoSongLyricsContributionMetadata.Instance)))!
            .Shape.Should().Be(CoSongLyricsContributionMetadata.Shape);

        // The marker now matches: a second start rebuilds nothing.
        await SeedAsync(async session => (await session.LoadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn"))).Text = "hand edit");
        await StartAsync(seedSong: false);
        (await ReadAsync<CoSongLyricsCurrent>(CurrentId("en", "Latn")))!.Text.Should().Be("hand edit");
    }

    // ---- models ---------------------------------------------------------------------------------------

    private static EntityTypeFile SongModel() => new()
    {
        PersistentObject = new EntityTypeDefinition
        {
            Id = SongTypeId,
            Name = "CoSong",
            ClrType = typeof(CoSong).FullName!,
            Breadcrumb = "{Title}",
            Attributes =
            [
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Title", DataType = "string" },
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Lyrics", DataType = "AsDetail", AsDetailType = typeof(CoLyrics).FullName, IsArray = true },
            ],
        },
    };

    private static EntityTypeFile LyricsModel() => new()
    {
        PersistentObject = new EntityTypeDefinition
        {
            Id = LyricsTypeId,
            Name = "CoLyrics",
            ClrType = typeof(CoLyrics).FullName!,
            Breadcrumb = "{Language}/{Script}",
            Attributes =
            [
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Language", DataType = "string" },
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Script", DataType = "string" },
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Text", DataType = "string" },
            ],
        },
    };

    private static EntityTypeFile ContributionModel() => new()
    {
        PersistentObject = new EntityTypeDefinition
        {
            Id = ContributionTypeId,
            Name = "CoSongLyricsContribution",
            ClrType = typeof(CoSongLyricsContribution).FullName!,
            Breadcrumb = "{Language}/{Script}",
            Attributes =
            [
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Language", DataType = "string" },
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Script", DataType = "string" },
                new EntityAttributeDefinition { Id = Guid.NewGuid(), Name = "Text", DataType = "string" },
            ],
        },
    };
}

// ---- fixtures (generated: CoSongLyricsContribution, CoSongLyricsCurrent, CoSongLyricsContributionMetadata, CoLyrics.Key) ----

public class CoSong
{
    public string? Id { get; set; }
    public string Title { get; set; } = string.Empty;

    [Contribution(Attribution = ContributionAttribution.Contributor | ContributionAttribution.UpdatedAt | ContributionAttribution.History)]
    [Newtonsoft.Json.JsonIgnore]
    public List<CoLyrics> Lyrics { get; set; } = [];
}

public partial class CoLyrics
{
    [ContributionSlot] public string Language { get; set; } = string.Empty;
    [ContributionSlot] public string Script { get; set; } = string.Empty;
    public string Text { get; set; } = string.Empty;
}

public sealed class CoIdentity
{
    public string? Id { get; set; }
}

public sealed class CoCurrentUser(CoIdentity identity) : ISparkCurrentUser
{
    public string? Id => identity.Id;
    public bool IsAuthenticated => identity.Id is not null;
}

public sealed class CoValidator : IContributionValidator<CoLyrics>
{
    public ValueTask<IReadOnlyList<ValidationError>> ValidateAsync(string targetId, CoLyrics element, CancellationToken cancellationToken = default)
        => ValueTask.FromResult<IReadOnlyList<ValidationError>>(element.Text.Contains("forbidden")
            ? [new ValidationError { AttributeName = "Text", ErrorMessage = TranslatedString.Create("That text is not allowed."), RuleType = "Custom" }]
            : []);
}

public sealed class CoLockedGuard : ISatelliteWriteGuard
{
    public ValueTask EnsureMayWriteAsync(SatelliteWriteContext context)
        => throw new SparkValidationException($"{context.DocumentType.Name} {context.DocumentId} is locked.");
}

/// <summary>Records the request session's request count around the contributions interceptor's hydration.</summary>
public sealed class CoProbe
{
    private readonly Dictionary<object, int> before = new(ReferenceEqualityComparer.Instance);
    public List<int> LoadDeltas { get; } = [];

    public void Clear()
    {
        lock (LoadDeltas) { before.Clear(); LoadDeltas.Clear(); }
    }

    public void Before(object entity, int requests)
    {
        lock (LoadDeltas) before[entity] = requests;
    }

    public void After(object entity, int requests)
    {
        lock (LoadDeltas)
            if (before.Remove(entity, out var start))
                LoadDeltas.Add(requests - start);
    }
}

public sealed class CoProbeBefore(CoProbe probe) : IPersistentObjectInterceptor
{
    public int Order => PersistentObjectInterceptorOrder.Contributions - 1;
    public bool AppliesTo(Type entityType) => entityType == typeof(CoSong);

    public ValueTask OnAfterMaterializeAsync(MaterializeContext context)
    {
        if (context.Reason == MaterializeReason.Load)
            probe.Before(context.Entity, context.GetSession().Advanced.NumberOfRequests);
        return ValueTask.CompletedTask;
    }
}

public sealed class CoProbeAfter(CoProbe probe) : IPersistentObjectInterceptor
{
    public int Order => PersistentObjectInterceptorOrder.Contributions + 1;
    public bool AppliesTo(Type entityType) => entityType == typeof(CoSong);

    public ValueTask OnAfterMaterializeAsync(MaterializeContext context)
    {
        if (context.Reason == MaterializeReason.Load)
            probe.After(context.Entity, context.GetSession().Advanced.NumberOfRequests);
        return ValueTask.CompletedTask;
    }
}

/// <summary>
/// Bob's save, landing between Alice's reads and her write: after the contributions interceptor stored
/// with its pinned change vectors, before the commit — like <c>ConcurrentWriteRaceTests</c>.
/// </summary>
public sealed class CoRace(IDocumentStore store)
{
    private string? armedFor;
    public bool Fired { get; private set; }

    public void Arm(string targetId) => armedFor = targetId;

    public async Task FireIfArmedAsync(string? targetId)
    {
        if (armedFor is null || armedFor != targetId)
            return;
        armedFor = null;

        using var session = store.OpenAsyncSession();
        var contribution = CoSongLyricsContributionMetadata.Instance.CreateContribution(targetId,
            new CoLyrics { Language = "en", Script = "Latn", Text = "bob's concurrent text" }, "users/bob", DateTime.UtcNow);
        await session.StoreAsync(contribution, contribution.Id);
        var current = CoSongLyricsContributionMetadata.Instance.CreateCurrent(contribution, 1);
        var existing = await session.LoadAsync<CoSongLyricsCurrent>(current.Id);
        if (existing is not null)
            session.Advanced.Evict(existing);
        await session.StoreAsync(current, current.Id);
        await session.SaveChangesAsync();
        Fired = true;
    }
}

public sealed class CoRaceInterceptor(CoRace race) : IPersistentObjectInterceptor
{
    public int Order => PersistentObjectInterceptorOrder.Contributions + 10;
    public bool AppliesTo(Type entityType) => entityType == typeof(CoSong);

    public async ValueTask OnBeforeSaveAsync(SaveContext context) => await race.FireIfArmedAsync(context.PersistentObject.Id);
}
