using Microsoft.CodeAnalysis;
using MintPlayer.Spark.SourceGenerators.Diagnostics;
using MintPlayer.Spark.SourceGenerators.Models;
using System;
using System.Linq;

namespace MintPlayer.Spark.SourceGenerators.Generators;

/// <summary>
/// Records, in an application, which referenced assemblies ship layers:
/// <c>[assembly: SparkLayerAssemblies("MintPlayer.Spark", …)]</c>, in layer order (composition D1,
/// amended by S1; D2).
/// </summary>
/// <remarks>
/// The compiler drops a reference whose types the application never uses, so a library that ships
/// only layers is visible here and missing from the run time's reference walk. The run time loads
/// exactly the recorded names instead. Two libraries with the same alias are SPARK043; the run time
/// refuses to start with them too.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ApplicationLayersGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var info = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var isApplication = compilation.Options.OutputKind is OutputKind.ConsoleApplication or OutputKind.WindowsApplication;
            if (!isApplication || compilation.GetTypeByMetadataName(LibraryLayersReader.AssembliesAttribute) is null)
                return new ApplicationLayersInfo();

            var libraries = LibraryLayersReader.Read(compilation);
            var duplicates = libraries
                .GroupBy(l => l.Alias, StringComparer.Ordinal)
                .Where(g => g.Count() > 1)
                .Select(g => new DuplicateAliasInfo { Alias = g.Key, First = g.First().Assembly, Second = g.Skip(1).First().Assembly })
                .ToList();

            return new ApplicationLayersInfo
            {
                ShouldEmit = libraries.Count > 0,
                Assemblies = libraries.Select(l => l.Assembly).ToList(),
                Duplicates = duplicates,
            };
        });

        context.RegisterSourceOutput(info, static (spc, info) =>
        {
            foreach (var duplicate in info.Duplicates)
                spc.ReportDiagnostic(Diagnostic.Create(LibraryLayersDiagnostics.DuplicateAlias, Location.None, duplicate.Alias, duplicate.First, duplicate.Second));

            if (!info.ShouldEmit) return;
            spc.AddSource("SparkLayerAssemblies.g.cs",
                "// <auto-generated/>\n"
                + "[assembly: global::MintPlayer.Spark.Abstractions.SparkLayerAssembliesAttribute("
                + string.Join(", ", info.Assemblies.Select(LibraryLayersGenerator.Literal))
                + ")]\n");
        });
    }
}
