using Microsoft.CodeAnalysis;
using MintPlayer.Spark.Layering;
using MintPlayer.Spark.SourceGenerators.Diagnostics;
using MintPlayer.Spark.SourceGenerators.Json;
using MintPlayer.Spark.SourceGenerators.Models;
using System;
using System.IO;
using System.Linq;
using System.Text;

namespace MintPlayer.Spark.SourceGenerators.Generators;

/// <summary>
/// Compiles a library's <c>App_Data</c> layer files into <c>[assembly: SparkLayer(alias, kind, path, json)]</c>
/// (composition D1). One generator for every kind; it replaces the per-kind actions and translations
/// generators.
/// </summary>
/// <remarks>
/// <para>
/// Only an AdditionalFile carrying <c>SparkLayerPath</c> metadata is a layer. The library targets
/// (<c>MintPlayer.Spark.SourceGenerators.targets</c>) add them for a class library; an application's
/// own files are AdditionalFiles too (for the analyzers) but carry no such metadata, are read from disk
/// at run time so they reload, and an executable embeds nothing, so an application is never a library
/// layer underneath itself (S3).
/// </para>
/// <para>
/// The text is passed through unparsed; the run time composes and validates it. Every
/// <c>translations.json</c> the compiler sees, layer or not, is still checked here
/// (SPARK_TRANS_001–004), as the translations generator did before.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class LibraryLayersGenerator : IIncrementalGenerator
{
    internal const string PathMetadata = "build_metadata.AdditionalFiles.SparkLayerPath";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var translations = context.AdditionalTextsProvider
            .Where(static t => string.Equals(Path.GetFileName(t.Path), "translations.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (t, ct) => CheckTranslations(t.Path, t.GetText(ct)?.ToString()));

        context.RegisterSourceOutput(translations, static (spc, info) => ReportTranslations(spc, info));

        var files = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (p, ct) =>
            {
                if (!p.Right.GetOptions(p.Left).TryGetValue(PathMetadata, out var path) || string.IsNullOrWhiteSpace(path))
                    return null;

                path = path.Trim().Replace('\\', '/');
                return SparkLayerKinds.FromPath(path) is { } kind
                    ? new LibraryLayerFileInfo { Path = path, Kind = kind, Text = p.Left.GetText(ct)?.ToString() ?? string.Empty }
                    : null;
            })
            .Where(static f => f is not null)
            .Select(static (f, _) => f!)
            .Collect();

        var alias = context.AnalyzerConfigOptionsProvider
            .Select(static (o, _) => o.GlobalOptions.TryGetValue(LibraryLayersDiagnostics.AliasProperty, out var a) ? a.Trim() : string.Empty);

        var compilation = context.CompilationProvider
            .Select(static (c, _) => new LibraryLayersCompilationInfo
            {
                IsLibrary = c.Options.OutputKind is OutputKind.DynamicallyLinkedLibrary or OutputKind.NetModule,
                Dependencies = LibraryLayersReader.Read(c).Select(l => l.Assembly).ToList(),
            });

        context.RegisterSourceOutput(files.Combine(alias).Combine(compilation), static (spc, input) =>
        {
            var ((all, alias), compilation) = input;
            if (!compilation.IsLibrary) return;

            // One per path: a file added twice (by these targets and by an application's) is one layer.
            var layers = all
                .Where(f => f.Text.Trim().Length > 0)
                .GroupBy(f => f.Path, StringComparer.Ordinal)
                .Select(g => g.First())
                .OrderBy(f => f.Path, StringComparer.Ordinal)
                .ToList();
            if (layers.Count == 0) return;

            if (LibraryLayersDiagnostics.AliasProblem(alias) is { } problem)
            {
                spc.ReportDiagnostic(Diagnostic.Create(LibraryLayersDiagnostics.AliasRequired, Location.None, layers.Count, problem));
                return;
            }
            if (LibraryLayersDiagnostics.GenericAliases.Contains(alias))
                spc.ReportDiagnostic(Diagnostic.Create(LibraryLayersDiagnostics.AliasTooGeneric, Location.None, alias));

            var source = new StringBuilder("// <auto-generated/>\n");
            foreach (var layer in layers)
            {
                source.Append("[assembly: global::MintPlayer.Spark.Abstractions.SparkLayerAttribute(")
                    .Append(Literal(alias)).Append(", ")
                    .Append(Literal(layer.Kind)).Append(", ")
                    .Append(Literal(layer.Path)).Append(", ")
                    .Append(Literal(layer.Text)).Append(")]\n");
            }
            if (compilation.Dependencies.Count > 0)
            {
                source.Append("[assembly: global::MintPlayer.Spark.Abstractions.SparkLayerDependenciesAttribute(")
                    .Append(string.Join(", ", compilation.Dependencies.Select(Literal)))
                    .Append(")]\n");
            }

            spc.AddSource("SparkLayers.g.cs", source.ToString());
        });
    }

    private static TranslationsLibraryInfo CheckTranslations(string path, string? text)
    {
        var info = new TranslationsLibraryInfo { FilePath = path, Parsed = true };
        if (string.IsNullOrEmpty(text)) return info;

        JsonNode parsed;
        try
        {
            parsed = MiniJson.Parse(text!);
        }
        catch (JsonParseException ex)
        {
            info.Parsed = false;
            info.ParseError = ex.Message;
            return info;
        }

        info.Issues = TranslationsTreeFlattener.Flatten(parsed).Issues
            .Select(i => new TranslationsIssueInfo { Kind = i.Kind.ToString(), Path = i.Path })
            .ToList();
        return info;
    }

    private static void ReportTranslations(SourceProductionContext spc, TranslationsLibraryInfo info)
    {
        if (!info.Parsed)
        {
            spc.ReportDiagnostic(Diagnostic.Create(TranslationsDiagnostics.InvalidJson, Location.None, info.ParseError));
            return;
        }

        foreach (var issue in info.Issues)
        {
            var descriptor = issue.Kind switch
            {
                nameof(TranslationsIssueKind.MixedLeafAndNamespace) => TranslationsDiagnostics.MixedLeafAndNamespace,
                nameof(TranslationsIssueKind.EmptyObject) => TranslationsDiagnostics.EmptyObject,
                nameof(TranslationsIssueKind.ArrayNotAllowed) => TranslationsDiagnostics.ArrayNotAllowed,
                _ => TranslationsDiagnostics.InvalidJson,
            };
            spc.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, issue.Path));
        }
    }

    /// <summary>A regular C# string literal for any text; attribute blobs have no practical size limit (S1).</summary>
    internal static string Literal(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\0': sb.Append("\\0"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20 || c == 0x7f || c == 0x85 || c == 0x2028 || c == 0x2029)
                        sb.AppendFormat(System.Globalization.CultureInfo.InvariantCulture, "\\u{0:x4}", (int)c);
                    else
                        sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
