using Microsoft.CodeAnalysis;
using System.IO;
using System.Linq;

namespace MintPlayer.Spark.SourceGenerators.Generators;

/// <summary>
/// Compiles a library's <c>App_Data/actions.json</c> into <c>[assembly: SparkActions("&lt;raw json&gt;")]</c>
/// (#467, D7/S12). Only an AdditionalFile marked <c>SparkActionsLayer="library"</c> counts: an
/// application's own <c>actions.json</c> is also an AdditionalFile (for the analyzers), but it is read
/// from disk at run time so it reloads, and compiling it too would make the application a library
/// layer underneath itself.
/// </summary>
/// <remarks>
/// The text is passed through unparsed. The generators' JSON reader handles strings only, and an
/// action has numbers and booleans; the run-time composition validates the catalogue.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class LibraryActionsGenerator : IIncrementalGenerator
{
    internal const string LayerMetadata = "build_metadata.AdditionalFiles.SparkActionsLayer";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var library = context.AdditionalTextsProvider
            .Where(static t => string.Equals(Path.GetFileName(t.Path), "actions.json", System.StringComparison.OrdinalIgnoreCase))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Where(static p => p.Right.GetOptions(p.Left).TryGetValue(LayerMetadata, out var layer)
                && string.Equals(layer, "library", System.StringComparison.OrdinalIgnoreCase))
            .Select(static (p, ct) => p.Left.GetText(ct)?.ToString() ?? string.Empty)
            .Collect();

        context.RegisterSourceOutput(library, static (spc, texts) =>
        {
            var text = texts.FirstOrDefault(t => t.Trim().Length > 0);
            if (text is null) return;

            var literal = LibraryTranslationsProducer.BuildCSharpStringLiteral(text);
            spc.AddSource("SparkActionsAssemblyAttribute.g.cs",
                "// <auto-generated/>\n"
                + $"[assembly: global::MintPlayer.Spark.Abstractions.SparkActionsAttribute({literal})]\n");
        });
    }
}
