using System.Collections.Concurrent;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace MintPlayer.Spark.Contributions;

/// <summary>
/// The runtime view of <see cref="ContributionRegistry"/>: one typed <see cref="IContributionHandler"/> per
/// declaration, created on first use. Nothing is scanned — the registry is filled by the generated
/// module initializers, and this class only makes sure those have run.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why module initializers need help.</b> A <c>[ModuleInitializer]</c> runs at the first access to
/// code of its module, not when the assembly is loaded, and loading a type through reflection (as the
/// model does) is not such an access. Three things trigger it, from the cheapest to the most explicit:
/// </para>
/// <list type="number">
/// <item><see cref="ForTarget"/> / <see cref="ForContribution"/> run the module constructor of the type
/// they are asked about — the interceptor's <c>AppliesTo</c> sees every model entity type, so every
/// declaring assembly that owns a model type is covered lazily;</item>
/// <item><c>AddContributions()</c> runs it for the entry assembly and those of its direct references that
/// reference <c>MintPlayer.Spark.Contributions.Abstractions</c> (only a declaring assembly does), so the
/// startup shape check sees them before any request;</item>
/// <item><c>AddContributions(typeof(Song).Assembly, …)</c> names declaring assemblies explicitly — needed
/// only when neither of the above reaches them (a test host, whose entry assembly is the test runner).</item>
/// </list>
/// <para>The one reflection call is <c>MakeGenericType</c>, once per declaration.</para>
/// </remarks>
internal sealed class ContributionCatalog
{
    private const string AbstractionsAssemblyName = "MintPlayer.Spark.Contributions.Abstractions";

    private readonly ConcurrentDictionary<ContributionDescriptor, IContributionHandler> handlers = new(ReferenceEqualityComparer.Instance);

    /// <summary>Every declaration registered so far.</summary>
    public IReadOnlyList<IContributionHandler> All => [.. ContributionRegistry.Descriptors.Select(Get)];

    /// <summary>The declarations whose target is <paramref name="entityType"/> (none for most types).</summary>
    public IReadOnlyList<IContributionHandler> ForTarget(Type entityType)
    {
        EnsureInitialized(entityType);
        return [.. ContributionRegistry.ForTarget(entityType).Select(Get)];
    }

    /// <summary>The declaration whose generated contribution type is <paramref name="entityType"/>, if any.</summary>
    public IContributionHandler? ForContribution(Type entityType)
    {
        EnsureInitialized(entityType);
        var descriptor = ContributionRegistry.Descriptors.FirstOrDefault(d => d.ContributionType == entityType);
        return descriptor is null ? null : Get(descriptor);
    }

    /// <summary>The declaration whose generated current type is <paramref name="entityType"/>, if any.</summary>
    public IContributionHandler? ForCurrent(Type entityType)
    {
        EnsureInitialized(entityType);
        var descriptor = ContributionRegistry.Descriptors.FirstOrDefault(d => d.CurrentType == entityType);
        return descriptor is null ? null : Get(descriptor);
    }

    /// <summary>The declaration whose generated contribution type has the full name <paramref name="clrType"/> (a model file's <c>clrType</c>).</summary>
    public IContributionHandler? ForContributionClrType(string? clrType)
    {
        if (string.IsNullOrEmpty(clrType))
            return null;
        var descriptor = ContributionRegistry.Descriptors.FirstOrDefault(d => string.Equals(d.ContributionType.FullName, clrType, StringComparison.Ordinal));
        return descriptor is null ? null : Get(descriptor);
    }

    private IContributionHandler Get(ContributionDescriptor descriptor) => handlers.GetOrAdd(descriptor, static d =>
    {
        var typed = d.GetType();
        while (typed is not null && !(typed.IsGenericType && typed.GetGenericTypeDefinition() == typeof(ContributionDescriptor<,,,>)))
            typed = typed.BaseType;
        if (typed is null)
            throw new InvalidOperationException(
                $"Contribution descriptor {d.GetType().FullName} does not derive from ContributionDescriptor<TTarget, TElement, TContribution, TCurrent>; it was not generated by MintPlayer.Spark.Contributions.");
        var handlerType = typeof(ContributionHandler<,,,>).MakeGenericType(typed.GetGenericArguments());
        return (IContributionHandler)Activator.CreateInstance(handlerType, d)!;
    });

    /// <summary>Runs the module initializer of <paramref name="type"/>'s module (idempotent, cheap after the first call).</summary>
    public static void EnsureInitialized(Type type) => RuntimeHelpers.RunModuleConstructor(type.Module.ModuleHandle);

    /// <summary>Runs the module initializer of <paramref name="assembly"/>.</summary>
    public static void EnsureInitialized(Assembly assembly) => RuntimeHelpers.RunModuleConstructor(assembly.ManifestModule.ModuleHandle);

    /// <summary>
    /// The entry assembly and those of its direct references that reference the contributions
    /// abstractions. Framework and RavenDB assemblies are skipped by name, without loading them.
    /// </summary>
    public static void EnsureEntryAssembliesInitialized()
    {
        var entry = Assembly.GetEntryAssembly();
        if (entry is null)
            return;
        if (DeclaresContributions(entry))
            EnsureInitialized(entry);

        foreach (var name in entry.GetReferencedAssemblies())
        {
            if (IsPlatform(name.Name))
                continue;
            Assembly referenced;
            try
            {
                referenced = Assembly.Load(name);
            }
            catch (Exception ex) when (ex is FileNotFoundException or FileLoadException or BadImageFormatException)
            {
                continue;
            }
            if (DeclaresContributions(referenced))
                EnsureInitialized(referenced);
        }
    }

    private static bool DeclaresContributions(Assembly assembly)
        => assembly.GetReferencedAssemblies().Any(n => string.Equals(n.Name, AbstractionsAssemblyName, StringComparison.Ordinal));

    private static bool IsPlatform(string? name)
        => name is null
           || name is "netstandard" or "mscorlib"
           || name.StartsWith("System", StringComparison.Ordinal)
           || name.StartsWith("Microsoft.", StringComparison.Ordinal)
           || name.StartsWith("Raven.", StringComparison.Ordinal)
           || name.StartsWith("Sparrow", StringComparison.Ordinal);
}
