namespace MintPlayer.Spark.Authorization.Identity;

/// <summary>
/// Base user class for Spark authentication backed by RavenDB.
/// All data is embedded in a single document. Extend this class
/// to add custom properties to the user document.
/// <example>
/// <code>
/// public class AppUser : SparkUser
/// {
///     public string DisplayName { get; set; }
/// }
/// </code>
/// </example>
/// </summary>
public class SparkUser
{
    public string? Id { get; set; }
    public string? UserName { get; set; }
    public string? NormalizedUserName { get; set; }
    public string? Email { get; set; }
    public string? NormalizedEmail { get; set; }
    public bool EmailConfirmed { get; set; }
    public string? PasswordHash { get; set; }
    public string? SecurityStamp { get; set; }
    public string? ConcurrencyStamp { get; set; } = Guid.NewGuid().ToString();
    public string? PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public DateTimeOffset? LockoutEnd { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }

    /// <summary>
    /// The TOTP authenticator key, stored protected (<c>sdp1:</c> + Data Protection) by the store.
    /// Read it through <c>UserManager.GetAuthenticatorKeyAsync</c>, never from this property.
    /// </summary>
    public string? AuthenticatorKey { get; set; }

    /// <summary>
    /// When the account was created (UTC). Stamped by the store on create; <see langword="null"/> for
    /// an account created before the field existed and not yet backfilled.
    /// </summary>
    public DateTime? CreatedAtUtc { get; set; }

    /// <summary>
    /// How the account was created — one of <c>SparkRegistrationMethods</c>
    /// (<c>password</c>, <c>external:{provider}</c>, <c>other</c>); <see langword="null"/> when unknown
    /// (accounts that predate the field).
    /// </summary>
    public string? RegistrationMethod { get; set; }

    /// <summary>
    /// The culture the user's mail is written in (<c>nl-BE</c>, <c>fr</c>), or null for
    /// <c>Spark:Mail:DefaultCulture</c> (#460, M8). Read when a mail is queued, never the request's
    /// culture: account mail renders on a worker.
    /// </summary>
    public string? PreferredCulture { get; set; }

    public List<string> Roles { get; set; } = [];
    public List<SparkUserClaim> Claims { get; set; } = [];
    public List<SparkUserLogin> Logins { get; set; } = [];
    /// <summary>
    /// SHA-256 hashes of the user's two-factor recovery codes — never the codes themselves.
    /// <para>
    /// A recovery code is a standing second-factor bypass, so storing it in the clear makes a
    /// database dump a dump of working bypasses for every user. Identity's own stores keep these
    /// in the clear; this package already refused that argument once, for <c>OidcToken</c>, and
    /// refuses it here for the same reason.
    /// </para>
    /// <para>
    /// A plain hash suffices — codes are generated by us with full entropy, so there is nothing
    /// for a dictionary to guess and no need for a per-code salt or work factor.
    /// </para>
    /// </summary>
    public List<string> TwoFactorRecoveryCodes { get; set; } = [];
    /// <summary>External-login tokens; each value is stored protected (<c>sdp1:</c>) by the store.</summary>
    public List<SparkUserToken> Tokens { get; set; } = [];

    /// <summary>
    /// WebAuthn credentials (passkeys) the user has enrolled.
    /// <para>
    /// Unlike the other collections here, membership is mirrored outside the document: each entry
    /// holds a cluster-wide compare/exchange reservation keyed on a hash of its credential id, so
    /// that a credential can be resolved to its owner without an index read and cannot be claimed by
    /// two users. Mutating this list directly bypasses that — go through the store.
    /// </para>
    /// </summary>
    public List<SparkUserPasskey> Passkeys { get; set; } = [];
}
