using MintPlayer.Spark.Abstractions;

namespace MintPlayer.Spark.IdentityProvider.Models;

/// <summary>
/// An OIDC client application registered with the identity provider: the <c>OidcApplications</c>
/// collection (<c>docs/identity_provider_platform_PRD.md</c> D1). It carries the client settings, its
/// secrets, its scopes, its members (D3), its mode (D4), its branding and its per-client protocol
/// settings (D8).
/// </summary>
public class OidcApplication
{
    /// <summary>Unique identifier of the client application, assigned automatically on creation.</summary>
    public string? Id { get; set; }

    // --- Identity ---
    /// <summary>Public client identifier the application sends in every OIDC request. Generated when the application is created, and read-only afterwards.</summary>
    public string ClientId { get; set; } = string.Empty;
    /// <summary>Human-readable name of the application, shown to users on the consent screen.</summary>
    public string DisplayName { get; set; } = string.Empty;
    /// <summary>Either <c>confidential</c> for a server that can keep a secret, or <c>public</c> for a browser or mobile app that cannot.</summary>
    public string ClientType { get; set; } = "confidential"; // "public" or "confidential"
    /// <summary>Whether the application may currently sign users in; disable to block it without deleting it.</summary>
    public bool Enabled { get; set; } = true;

    // --- Ownership and lifecycle (D3, D4) ---
    /// <summary>The people who manage or test this application, with their role. The creator starts as Admin.</summary>
    public List<OidcApplicationMember> Members { get; set; } = [];
    /// <summary><c>Development</c>: only members can authorize the application. <c>Live</c>: anyone can.</summary>
    public string Mode { get; set; } = OidcApplicationModes.Development;
    /// <summary>The pending or decided request to switch to Live, when an administrator has to review it.</summary>
    public OidcReviewDecision? GoLiveReview { get; set; }
    /// <summary>The user who registered the application.</summary>
    public string? CreatedBy { get; set; }
    /// <summary>Moment the application was registered, in UTC.</summary>
    public DateTime? CreatedAt { get; set; }

    // --- Branding (D5) ---
    /// <summary>Address of the logo shown on the consent screen and in the user's connected applications.</summary>
    public string? LogoUrl { get; set; }
    /// <summary>The application's home page.</summary>
    public string? HomepageUrl { get; set; }
    /// <summary>The application's privacy policy, linked from the consent screen.</summary>
    public string? PrivacyPolicyUrl { get; set; }
    /// <summary>The application's terms of service, linked from the consent screen.</summary>
    public string? TermsOfServiceUrl { get; set; }
    /// <summary>Where users can reach the application's developers.</summary>
    public string? SupportEmail { get; set; }
    /// <summary>Who publishes the application, shown as "by &lt;publisher&gt;" on the consent screen.</summary>
    public string? Publisher { get; set; }

    // --- Secrets (supports rotation: multiple secrets with expiration) ---
    /// <summary>Secrets a confidential client authenticates with; several can coexist so a secret can be rotated. Generated by the Generate secret action and shown once.</summary>
    public List<ClientSecret> Secrets { get; set; } = [];

    // --- Grant types ---
    /// <summary>
    /// The grants this client may use. **Must not carry a non-empty initializer.**
    /// <para>
    /// RavenDB's serializer populates the collection the property initializer already created
    /// rather than replacing it, so a default of <c>["authorization_code"]</c> was silently
    /// re-added to every application on load. A client stored as <c>client_credentials</c>-only
    /// came back as <c>["authorization_code", "client_credentials"]</c> — which defeats the
    /// grant gating outright: the interactive flow accepted a machine client no matter what was
    /// configured, and the check that was supposed to stop it could never fail.
    /// </para>
    /// <para>
    /// Empty now means empty, so a client that declares no grants can use none — fail closed.
    /// </para>
    /// </summary>
    public List<string> AllowedGrantTypes { get; set; } = [];

    /// <summary>
    /// Lets this client introspect tokens it neither issued nor is the audience of.
    /// <para>
    /// Off by default: introspection discloses a token's subject and scopes, so the caller must
    /// have a reason to see them — it issued the token, or the token was minted for it. Turn this
    /// on only for a gateway that introspects on behalf of the resources behind it, and
    /// understand that it can then read every token in the system.
    /// </para>
    /// </summary>
    public bool MayIntrospectAnyAudience { get; set; }

    // --- URIs ---
    /// <summary>Exact URIs the identity provider may redirect back to after sign-in; any other URI is rejected.</summary>
    public List<string> RedirectUris { get; set; } = [];
    /// <summary>Exact URIs the identity provider may redirect back to after the user signs out.</summary>
    public List<string> PostLogoutRedirectUris { get; set; } = [];
    /// <summary>Browser origins allowed to call the OIDC endpoints cross-site, e.g. <c>https://app.example.com</c>.</summary>
    public List<string> AllowedCorsOrigins { get; set; } = [];

    // --- Scopes & Claims ---
    /// <summary>The scopes this application may request, each required or optional. A request for any other scope is refused.</summary>
    public List<OidcApplicationScope> Scopes { get; set; } = [];
    /// <summary>Fixed claims added to every token issued to this application.</summary>
    public List<ClientClaim> Claims { get; set; } = [];

    // --- Consent ---
    /// <summary>Either <c>explicit</c> to ask the user for consent on the consent screen, or <c>implicit</c> to grant it automatically.</summary>
    public string ConsentType { get; set; } = "explicit"; // "explicit" or "implicit"
    /// <summary>Whether the user may tick a box so the consent screen is skipped on later sign-ins.</summary>
    public bool AllowRememberConsent { get; set; } = true;
    /// <summary>How long, in seconds, a remembered consent stays valid; leave empty to keep it until withdrawn.</summary>
    public int? ConsentLifetimeSeconds { get; set; }

    // --- Token lifetimes ---
    /// <summary>Whether the authorization code flow must use PKCE; keep enabled unless a legacy client cannot support it.</summary>
    public bool RequirePkce { get; set; } = true;
    /// <summary>Validity of an issued access token in minutes.</summary>
    public int AccessTokenLifetimeMinutes { get; set; } = 60;
    /// <summary>Validity of an issued ID token in minutes; it is only read once, at sign-in, so keep it short. Leave empty for the 5-minute default.</summary>
    // Optional on purpose: the field arrived after clients were already being registered, so a
    // create or update that does not carry it must still be accepted. Empty or 0 means the default
    // (see EffectiveIdTokenLifetimeMinutes), applied when the token is issued.
    public int? IdTokenLifetimeMinutes { get; set; } = DefaultIdTokenLifetimeMinutes;
    /// <summary>Validity of an issued refresh token in days.</summary>
    public int RefreshTokenLifetimeDays { get; set; } = 14;

    // --- Protocol (D8) ---
    /// <summary>
    /// How this client authenticates at the token endpoint: <c>client_secret_basic</c>,
    /// <c>client_secret_post</c>, <c>private_key_jwt</c>, <c>tls_client_auth</c>,
    /// <c>self_signed_tls_client_auth</c> or <c>none</c> (a public client). Leave empty to accept
    /// either secret method.
    /// </summary>
    public string? TokenEndpointAuthMethod { get; set; }
    /// <summary>The client's public keys as a JWKS document, for <c>private_key_jwt</c>, signed request objects and encrypted tokens.</summary>
    public string? Jwks { get; set; }
    /// <summary>Where the client publishes its JWKS, instead of <see cref="Jwks"/>.</summary>
    public string? JwksUri { get; set; }
    /// <summary>For <c>tls_client_auth</c>: the expected subject distinguished name of the client certificate.</summary>
    public string? TlsClientAuthSubjectDn { get; set; }
    /// <summary>Whether access tokens are bound to the client's certificate (RFC 8705).</summary>
    public bool TlsClientCertificateBoundAccessTokens { get; set; }
    /// <summary>Whether access tokens must be DPoP-bound (RFC 9449).</summary>
    public bool RequireDpop { get; set; }
    /// <summary>Whether the client must push its authorization requests first (PAR, RFC 9126).</summary>
    public bool RequirePushedAuthorizationRequests { get; set; }
    /// <summary>Whether the client must send its authorization requests as signed request objects (JAR, RFC 9101).</summary>
    public bool RequireSignedRequestObject { get; set; }
    /// <summary><c>public</c>: every client sees the same subject. <c>pairwise</c>: each sector sees its own.</summary>
    public string SubjectType { get; set; } = "public";
    /// <summary>For pairwise subjects: the URI naming the sector whose clients share a subject.</summary>
    public string? SectorIdentifierUri { get; set; }
    /// <summary>Algorithm the id_token is signed with; leave empty for RS256.</summary>
    public string? IdTokenSignedResponseAlg { get; set; }
    /// <summary>Key-management algorithm the id_token is encrypted with (e.g. <c>RSA-OAEP</c>); leave empty for no encryption.</summary>
    public string? IdTokenEncryptedResponseAlg { get; set; }
    /// <summary>Content-encryption algorithm for an encrypted id_token (e.g. <c>A256CBC-HS512</c>).</summary>
    public string? IdTokenEncryptedResponseEnc { get; set; }
    /// <summary>Algorithm the userinfo response is signed with; leave empty for plain JSON.</summary>
    public string? UserinfoSignedResponseAlg { get; set; }
    /// <summary>Key-management algorithm the userinfo response is encrypted with; leave empty for no encryption.</summary>
    public string? UserinfoEncryptedResponseAlg { get; set; }
    /// <summary>Content-encryption algorithm for an encrypted userinfo response.</summary>
    public string? UserinfoEncryptedResponseEnc { get; set; }
    /// <summary>Default maximum authentication age in seconds, as if every request carried <c>max_age</c>.</summary>
    public int? DefaultMaxAge { get; set; }
    /// <summary>Where the identity provider posts a logout token when the user's session ends (back-channel logout).</summary>
    public string? BackChannelLogoutUri { get; set; }
    /// <summary>Whether the back-channel logout token must carry the session id (<c>sid</c>).</summary>
    public bool BackChannelLogoutSessionRequired { get; set; }
    /// <summary>The page the logout page loads in an iframe when the user signs out (front-channel logout).</summary>
    public string? FrontChannelLogoutUri { get; set; }
    /// <summary>Whether the front-channel logout URI receives <c>iss</c> and <c>sid</c>.</summary>
    public bool FrontChannelLogoutSessionRequired { get; set; }
    /// <summary>Whether a token exchange by this client may impersonate the subject rather than only act on its behalf (RFC 8693).</summary>
    public bool AllowImpersonation { get; set; }

    /// <summary>The id_token lifetime used when <see cref="IdTokenLifetimeMinutes"/> is empty or not positive.</summary>
    public const int DefaultIdTokenLifetimeMinutes = 5;

    /// <summary>The id_token lifetime to issue with: <see cref="IdTokenLifetimeMinutes"/>, or the default when it is empty or not positive.</summary>
    public int EffectiveIdTokenLifetimeMinutes()
        => IdTokenLifetimeMinutes is int minutes and > 0 ? minutes : DefaultIdTokenLifetimeMinutes;

    /// <summary>The names of the scopes this application may request.</summary>
    public IEnumerable<string> ScopeNames() => Scopes.Select(s => s.Name);

    /// <summary>The member entry of an active member, or null.</summary>
    public OidcApplicationMember? ActiveMember(string? userId)
        => userId is null ? null : Members.FirstOrDefault(m =>
            m.Status == OidcMemberStatuses.Active && string.Equals(m.UserId, userId, StringComparison.Ordinal));
}

/// <summary>The values of <see cref="OidcApplication.Mode"/>.</summary>
public static class OidcApplicationModes
{
    /// <summary>Only the application's members can authorize it; nothing needs approval.</summary>
    public const string Development = "Development";
    /// <summary>Anyone can authorize it; cross-owner API scopes need their owner's approval.</summary>
    public const string Live = "Live";
}

[ValueObject]
public partial class ClientSecret
{
    /// <summary>Identifies the secret for revocation, and appears in the audit trail; never the secret itself.</summary>
    public string? SecretId { get; set; }
    /// <summary>The client secret's hash. The plaintext is shown once, when the secret is generated, and never stored.</summary>
    public string Hash { get; set; } = string.Empty;
    /// <summary>Optional note telling secrets apart, e.g. <c>Production 2026</c>.</summary>
    public string? Description { get; set; }
    /// <summary>Moment the secret was created, in UTC.</summary>
    public DateTime CreatedAt { get; set; }
    /// <summary>Moment after which the secret is no longer accepted, in UTC; leave empty for a secret that never expires.</summary>
    public DateTime? ExpiresAt { get; set; }
    /// <summary>The last time the secret authenticated the client, in UTC, recorded at most once an hour.</summary>
    public DateTime? LastUsedAt { get; set; }
}

[ValueObject]
public partial class ClientClaim
{
    /// <summary>Claim type added to issued tokens, e.g. <c>tenant</c>.</summary>
    public string Type { get; set; } = string.Empty;
    /// <summary>Value issued for the claim type.</summary>
    public string Value { get; set; } = string.Empty;
}

/// <summary>One scope an application may request (D6, D4).</summary>
[ValueObject]
public partial class OidcApplicationScope
{
    /// <summary>The scope's name, e.g. <c>email</c> or <c>fleet.read</c>.</summary>
    public string Name { get; set; } = string.Empty;
    /// <summary>Whether the user must grant it. An optional scope can be unticked on the consent screen.</summary>
    public bool Required { get; set; }
    /// <summary><c>Approved</c>, or <c>Pending</c> while the owner of a cross-owner API scope has not approved it, or <c>Rejected</c>.</summary>
    public string Status { get; set; } = OidcScopeStatuses.Approved;
    /// <summary>Who approved or rejected the scope, and when.</summary>
    public OidcReviewDecision? Review { get; set; }
}

/// <summary>The values of <see cref="OidcApplicationScope.Status"/>.</summary>
public static class OidcScopeStatuses
{
    public const string Approved = "Approved";
    public const string Pending = "Pending";
    public const string Rejected = "Rejected";
}

/// <summary>A person on an application's team (D3).</summary>
[ValueObject]
public partial class OidcApplicationMember
{
    /// <summary>Identifies the entry for resend, revoke and remove.</summary>
    public string? MemberId { get; set; }
    /// <summary>The member's user id. Empty while an invitation is pending: an invitation never discloses whether the address has an account.</summary>
    public string? UserId { get; set; }
    /// <summary>The address the invitation was sent to, as typed.</summary>
    public string? Email { get; set; }
    /// <summary><c>Admin</c>, <c>Developer</c> or <c>Tester</c>.</summary>
    public string Role { get; set; } = OidcMemberRoles.Developer;
    /// <summary><c>Invited</c>, <c>Active</c>, or <c>Revoked</c>. An invitation past its expiry shows as expired.</summary>
    public string Status { get; set; } = OidcMemberStatuses.Invited;
    /// <summary>SHA-256 of the single-use invitation token. Cleared when the invitation is accepted.</summary>
    public string? InvitationHash { get; set; }
    /// <summary>When the invitation stops being accepted, in UTC.</summary>
    public DateTime? InvitationExpiresAt { get; set; }
    /// <summary>Who sent the invitation.</summary>
    public string? InvitedBy { get; set; }
    /// <summary>When the invitation was sent, in UTC.</summary>
    public DateTime? InvitedAt { get; set; }
    /// <summary>When the invitation was accepted, in UTC.</summary>
    public DateTime? AcceptedAt { get; set; }
}

public static class OidcMemberRoles
{
    /// <summary>Everything: members, secrets, delete, mode switches, go-live requests.</summary>
    public const string Admin = "Admin";
    /// <summary>Settings, URIs and scopes. No secrets, no members.</summary>
    public const string Developer = "Developer";
    /// <summary>No portal access; may authorize the application while it is in Development mode.</summary>
    public const string Tester = "Tester";
}

public static class OidcMemberStatuses
{
    public const string Invited = "Invited";
    public const string Active = "Active";
    public const string Revoked = "Revoked";
}

/// <summary>A request that someone decides on: a go-live review, a scope approval, a developer request.</summary>
[ValueObject]
public partial class OidcReviewDecision
{
    /// <summary><c>Pending</c>, <c>Approved</c> or <c>Rejected</c>.</summary>
    public string Status { get; set; } = OidcScopeStatuses.Pending;
    /// <summary>Who asked, and when, in UTC.</summary>
    public string? RequestedBy { get; set; }
    public DateTime? RequestedAt { get; set; }
    /// <summary>Who decided, and when, in UTC.</summary>
    public string? DecidedBy { get; set; }
    public DateTime? DecidedAt { get; set; }
    /// <summary>The reason given with the decision.</summary>
    public string? Note { get; set; }
}
