using MintPlayer.SourceGenerators.Attributes;
using MintPlayer.Spark.Abstractions;

namespace MintPlayer.Spark.Endpoints.PersistentObject;

[Register(ServiceLifetime.Scoped, "AddSparkServices")]
public sealed partial class CreatePersistentObject
{
    [Inject] private readonly IDatabaseAccess databaseAccess;

    public async Task HandleAsync(HttpContext httpContext, Guid objectTypeId)
    {
        var obj = await httpContext.Request.ReadFromJsonAsync<Abstractions.PersistentObject>()
            ?? throw new InvalidOperationException("PersistentObject could not be deserialized from the request body.");

        // Ensure the ObjectTypeId matches the URL parameter
        obj.ObjectTypeId = objectTypeId;

        // Maps to actual entity and saves - ID will be generated by RavenDB
        var result = await databaseAccess.SavePersistentObjectAsync(obj);

        httpContext.Response.StatusCode = StatusCodes.Status201Created;
        await httpContext.Response.WriteAsJsonAsync(result);
    }
}
