using MintPlayer.SourceGenerators.Attributes;
using MintPlayer.Spark.Abstractions;
using MintPlayer.Spark.Services;

namespace MintPlayer.Spark.Endpoints.PersistentObject;

[Register(ServiceLifetime.Scoped)]
public sealed partial class CreatePersistentObject
{
    [Inject] private readonly IDatabaseAccess databaseAccess;
    [Inject] private readonly IValidationService validationService;

    public async Task HandleAsync(HttpContext httpContext, Guid objectTypeId)
    {
        var obj = await httpContext.Request.ReadFromJsonAsync<Abstractions.PersistentObject>()
            ?? throw new InvalidOperationException("PersistentObject could not be deserialized from the request body.");

        // Ensure the ObjectTypeId matches the URL parameter
        obj.ObjectTypeId = objectTypeId;

        // Validate the object
        var validationResult = validationService.Validate(obj);
        if (!validationResult.IsValid)
        {
            httpContext.Response.StatusCode = StatusCodes.Status400BadRequest;
            await httpContext.Response.WriteAsJsonAsync(new { errors = validationResult.Errors });
            return;
        }

        // Maps to actual entity and saves - ID will be generated by RavenDB
        var result = await databaseAccess.SavePersistentObjectAsync(obj);

        httpContext.Response.StatusCode = StatusCodes.Status201Created;
        await httpContext.Response.WriteAsJsonAsync(result);
    }
}
