using System.Text;

namespace MintPlayer.Spark.Contributions.SourceGenerators;

/// <summary>Writes the generated source for <see cref="ContributionModel"/>s.</summary>
internal static class ContributionsEmitter
{
    private const string Format = "global::MintPlayer.Spark.Contributions.ContributionSlotFormat";
    private const string HasNaturalId = "global::MintPlayer.Spark.Abstractions.IHasNaturalId";
    private const string Header = "// <auto-generated by MintPlayer.Spark.Contributions.SourceGenerators />\n#nullable enable\n";

    // ------------------------------------------------------------------ per declaration

    public static string Declaration(ContributionModel m)
    {
        var w = new Writer();
        w.Raw(Header);
        var access = m.IsPublic ? "public" : "internal";
        var ns = !string.IsNullOrEmpty(m.Namespace);
        if (ns) w.Open($"namespace {m.Namespace}");

        WriteContribution(w, m, access);
        w.Line();
        WriteCurrent(w, m, access);
        w.Line();
        WriteMetadata(w, m, access);

        if (ns) w.Close();
        return w.ToString();
    }

    private static void WriteContribution(Writer w, ContributionModel m, string access)
    {
        var interfaces = $"global::MintPlayer.Spark.Contributions.IContribution, {HasNaturalId}";
        if (m.IsSoftDeletable && m.EmitSoftDeleteMembers)
            interfaces += ", global::MintPlayer.Spark.SoftDelete.ISoftDeletable";

        w.Line("/// <summary>");
        w.Line($"/// One user's contribution to <see cref=\"{m.OwnerType}.{m.PropertyName}\"/>{(m.IsCollection ? " for one slot" : "")}. Id:");
        w.Line($"/// <c>{{targetId}}/{m.PropertyName}Contributions/{SlotPath(m)}User/{{userId}}</c>.");
        w.Line("/// </summary>");
        w.Line("/// <remarks>");
        w.Line("/// Generated by MintPlayer.Spark.Contributions; <c>partial</c>, so the app can add <c>IModeratable</c>.");
        w.Line("/// The type name is a RavenDB collection name and a <c>security.json</c> resource: renaming the");
        w.Line("/// target or the property means migrating both.");
        w.Line("/// </remarks>");
        w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"MintPlayer.Spark.Contributions.SourceGenerators\", \"1\")]");
        w.Open($"{access} partial class {m.ContributionName} : {interfaces}");

        w.Line("/// <summary>The document id; see <see cref=\"GetId\"/>.</summary>");
        w.Line("public string? Id { get; set; }");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line("public string TargetId { get; set; } = \"\";");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line("public string ContributorId { get; set; } = \"\";");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line("public global::System.DateTime UpdatedAt { get; set; }");
        WriteSlotAndValueProperties(w, m);

        if (m.IsSoftDeletable && m.EmitSoftDeleteMembers)
        {
            w.Line();
            w.Line("/// <inheritdoc />");
            w.Line("public bool IsDeleted { get; set; }");
            w.Line();
            w.Line("/// <inheritdoc />");
            w.Line("public global::System.DateTimeOffset? DeletedAt { get; set; }");
            w.Line();
            w.Line("/// <inheritdoc />");
            w.Line("public string? DeletedBy { get; set; }");
            w.Line();
            w.Line("/// <inheritdoc />");
            w.Line("public string? DeleteReason { get; set; }");
        }

        w.Line();
        w.Line($"/// <summary><c>{{targetId}}/{m.PropertyName}Contributions/{SlotPath(m)}User/{{userId}}</c>; the user id keeps its own slashes.</summary>");
        var parameters = string.Concat(m.Slots.Select(s => $", {s.Type} {s.ParameterName}"));
        w.Line($"public static string GetId(string targetId{parameters}, string userId)");
        w.Line($"    => targetId + \"/{m.PropertyName}Contributions/\"{SlotConcat(m, s => s.ParameterName)}{UserSegment(m)} + userId;");
        w.Line();
        var args = string.Concat(m.Slots.Select(s => $", {s.Name}"));
        w.Line($"string {HasNaturalId}.GetId() => GetId(TargetId{args}, ContributorId);");
        w.Close();
    }

    private static void WriteCurrent(Writer w, ContributionModel m, string access)
    {
        w.Line("/// <summary>");
        w.Line($"/// The current (latest non-hidden) version of <see cref=\"{m.OwnerType}.{m.PropertyName}\"/>{(m.IsCollection ? " for one slot" : "")}:");
        w.Line("/// a cache of one contribution, written in the same transaction, which the library can rebuild. Id:");
        w.Line($"/// <c>{{targetId}}/{m.PropertyName}{(m.IsCollection ? "/" + SlotPath(m).TrimEnd('/') : "")}</c>.");
        w.Line("/// </summary>");
        w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"MintPlayer.Spark.Contributions.SourceGenerators\", \"1\")]");
        w.Open($"{access} partial class {m.CurrentName} : global::MintPlayer.Spark.Contributions.ICurrentContribution, {HasNaturalId}");

        w.Line("/// <summary>The document id; see <see cref=\"GetId\"/>.</summary>");
        w.Line("public string? Id { get; set; }");
        w.Line();
        w.Line("/// <summary>The document id of the target entity (part of <see cref=\"Id\"/>).</summary>");
        w.Line("public string TargetId { get; set; } = \"\";");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line("public string ContributorId { get; set; } = \"\";");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line("public string ContributionId { get; set; } = \"\";");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line("public global::System.DateTime UpdatedAt { get; set; }");
        if (m.Has(ContributionModel.AttributionHistory))
        {
            w.Line();
            w.Line("/// <summary>How many contributions the slot has (<c>ContributionAttribution.History</c>).</summary>");
            w.Line("public int ContributionCount { get; set; }");
        }
        WriteSlotAndValueProperties(w, m);

        w.Line();
        var path = m.IsCollection ? "/" + SlotPath(m).TrimEnd('/') : "";
        w.Line($"/// <summary><c>{{targetId}}/{m.PropertyName}{path}</c>.</summary>");
        var parameters = string.Concat(m.Slots.Select(s => $", {s.Type} {s.ParameterName}"));
        w.Line($"public static string GetId(string targetId{parameters})");
        w.Line($"    => targetId + \"/{m.PropertyName}{(m.IsCollection ? "/" : "")}\"{SlotConcat(m, s => s.ParameterName)};");
        w.Line();
        var args = string.Concat(m.Slots.Select(s => $", {s.Name}"));
        w.Line($"string {HasNaturalId}.GetId() => GetId(TargetId{args});");
        w.Close();
    }

    private static void WriteSlotAndValueProperties(Writer w, ContributionModel m)
    {
        foreach (var slot in m.Slots)
        {
            w.Line();
            w.Line($"/// <summary>Slot, copied from <see cref=\"{m.Element.FullyQualified}.{slot.Name}\"/>.</summary>");
            w.Line($"public {slot.Type} {slot.Name} {{ get; set; }}{slot.Initializer}");
        }
        foreach (var value in m.Values)
        {
            w.Line();
            w.Line($"/// <summary>Copied from <see cref=\"{m.Element.FullyQualified}.{value.Name}\"/>.</summary>");
            w.Line($"public {value.Type} {value.Name} {{ get; set; }}{value.Initializer}");
        }
    }

    private static void WriteMetadata(Writer w, ContributionModel m, string access)
    {
        var e = m.Element.FullyQualified;
        var c = m.ContributionType;
        var cur = m.CurrentType;
        var baseType = $"global::MintPlayer.Spark.Contributions.ContributionDescriptor<{m.OwnerType}, {e}, {c}, {cur}>";

        w.Line("/// <summary>");
        w.Line($"/// Ids, accessors and mappings for <see cref=\"{m.OwnerType}.{m.PropertyName}\"/>, registered in");
        w.Line("/// <see cref=\"global::MintPlayer.Spark.Contributions.ContributionRegistry\"/> by this assembly's module initializer.");
        w.Line("/// </summary>");
        w.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"MintPlayer.Spark.Contributions.SourceGenerators\", \"1\")]");
        w.Open($"{access} sealed class {m.MetadataName} : {baseType}");

        w.Line("/// <summary>The one instance.</summary>");
        w.Line($"public static {m.MetadataName} Instance {{ get; }} = new();");
        w.Line();
        w.Line($"private {m.MetadataName}() {{ }}");
        w.Line();
        w.Line($"/// <summary>See <see cref=\"global::MintPlayer.Spark.Contributions.ContributionDescriptor.ShapeHash\"/>.</summary>");
        w.Line($"public const string Shape = \"{m.ShapeHash}\";");
        w.Line();
        w.Line($"/// <summary>The generated query over <see cref=\"{c}\"/>.</summary>");
        w.Line($"public const string QueryName = \"{m.QueryName}\";");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line($"public override string PropertyName => \"{m.PropertyName}\";");
        w.Line("/// <inheritdoc />");
        w.Line("public override string ContributionsQueryName => QueryName;");
        w.Line("/// <inheritdoc />");
        w.Line($"public override bool IsCollection => {(m.IsCollection ? "true" : "false")};");
        w.Line("/// <inheritdoc />");
        w.Line($"public override global::System.Collections.Generic.IReadOnlyList<string> SlotNames {{ get; }} = {StringArray(m.Slots.Select(s => s.Name))};");
        w.Line("/// <inheritdoc />");
        w.Line($"public override global::System.Collections.Generic.IReadOnlyList<string> ValueNames {{ get; }} = {StringArray(m.Values.Select(v => v.Name))};");
        w.Line("/// <inheritdoc />");
        w.Line($"public override global::MintPlayer.Spark.Contributions.ContributionAttribution Attribution => {AttributionExpression(m.Attribution)};");
        w.Line("/// <inheritdoc />");
        w.Line($"public override global::System.Collections.Generic.IReadOnlyList<string> AttributionAttributeNames {{ get; }} = {StringArray(AttributionNames(m.Attribution))};");
        w.Line("/// <inheritdoc />");
        w.Line($"public override bool IsSoftDeletable => {(m.IsSoftDeletable ? "true" : "false")};");
        w.Line("/// <inheritdoc />");
        w.Line("public override string ShapeHash => Shape;");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Line($"public override string ContributionPrefix(string targetId) => targetId + \"/{m.PropertyName}Contributions/\";");
        w.Line("/// <inheritdoc />");
        w.Line($"public override string CurrentPrefix(string targetId) => targetId + \"/{m.PropertyName}/\";");
        w.Line();

        // Rows
        w.Line("/// <inheritdoc />");
        w.Open($"public override global::System.Collections.Generic.IReadOnlyList<{e}> GetRows({m.OwnerType} target)");
        if (m.IsCollection)
            w.Line($"return target.{m.PropertyName} is {{ }} rows ? new global::System.Collections.Generic.List<{e}>(rows) : new global::System.Collections.Generic.List<{e}>();");
        else
            w.Line($"return target.{m.PropertyName} is {{ }} row ? new {e}[] {{ row }} : global::System.Array.Empty<{e}>();");
        w.Close();
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Open($"public override void SetRows({m.OwnerType} target, global::System.Collections.Generic.IReadOnlyList<{e}> rows)");
        if (!m.IsCollection)
        {
            w.Line($"target.{m.PropertyName} = rows.Count == 0 ? null! : rows[0];");
        }
        else if (!m.PropertyWritable)
        {
            w.Line($"var held = target.{m.PropertyName};");
            w.Line("held.Clear();");
            w.Line("foreach (var row in rows)");
            w.Line("    held.Add(row);");
        }
        else if (m.Shape == CollectionShape.Array)
        {
            w.Line($"target.{m.PropertyName} = global::System.Linq.Enumerable.ToArray(rows);");
        }
        else
        {
            w.Line($"target.{m.PropertyName} = new global::System.Collections.Generic.List<{e}>(rows);");
        }
        w.Close();
        w.Line();

        // Slots
        w.Line("/// <inheritdoc />");
        w.Line($"public override string SlotKeyOf({e} row) => {SlotKeyExpression(m, "row")};");
        w.Line("/// <inheritdoc />");
        w.Line($"public override string SlotKeyOfContribution({c} contribution) => {SlotKeyExpression(m, "contribution")};");
        w.Line("/// <inheritdoc />");
        w.Line($"public override string SlotKeyOfCurrent({cur} current) => {SlotKeyExpression(m, "current")};");
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Open($"public override string? FindInvalidSlot({e} row)");
        foreach (var slot in m.Slots)
            w.Line($"if (!{Format}.IsValid({slot.Format("row." + slot.Name)})) return \"{slot.Name}\";");
        w.Line("return null;");
        w.Close();
        w.Line();

        // Ids
        var rowSlots = string.Concat(m.Slots.Select(s => $", row.{s.Name}"));
        w.Line("/// <inheritdoc />");
        w.Line($"public override string ContributionId(string targetId, {e} row, string userId) => {c}.GetId(targetId{rowSlots}, userId);");
        w.Line("/// <inheritdoc />");
        w.Line($"public override string CurrentId(string targetId, {e} row) => {cur}.GetId(targetId{rowSlots});");
        w.Line("/// <inheritdoc />");
        w.Line($"public override string SlotContributionPrefix(string targetId, {e} row) => ContributionPrefix(targetId){SlotConcat(m, s => "row." + s.Name)}{UserSegment(m)};");
        w.Line();

        // Mappings
        w.Line("/// <inheritdoc />");
        w.Open($"public override {c} CreateContribution(string targetId, {e} row, string contributorId, global::System.DateTime updatedAtUtc)");
        w.Open($"return new {c}", trailer: "");
        w.Line($"Id = ContributionId(targetId, row, contributorId),");
        w.Line("TargetId = targetId,");
        w.Line("ContributorId = contributorId,");
        w.Line("UpdatedAt = updatedAtUtc,");
        foreach (var slot in m.Slots) w.Line($"{slot.Name} = row.{slot.Name},");
        foreach (var value in m.Values) w.Line($"{value.Name} = row.{value.Name},");
        w.Close(";");
        w.Close();
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Open($"public override void CopyValues({e} row, {c} contribution)");
        foreach (var value in m.Values) w.Line($"contribution.{value.Name} = row.{value.Name};");
        w.Close();
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Open($"public override {cur} CreateCurrent({c} contribution, int contributionCount)");
        var contributionSlots = string.Concat(m.Slots.Select(s => $", contribution.{s.Name}"));
        w.Open($"return new {cur}", trailer: "");
        w.Line($"Id = {cur}.GetId(contribution.TargetId{contributionSlots}),");
        w.Line("TargetId = contribution.TargetId,");
        w.Line("ContributorId = contribution.ContributorId,");
        w.Line($"ContributionId = {c}.GetId(contribution.TargetId{contributionSlots}, contribution.ContributorId),");
        w.Line("UpdatedAt = contribution.UpdatedAt,");
        if (m.Has(ContributionModel.AttributionHistory)) w.Line("ContributionCount = contributionCount,");
        foreach (var slot in m.Slots) w.Line($"{slot.Name} = contribution.{slot.Name},");
        foreach (var value in m.Values) w.Line($"{value.Name} = contribution.{value.Name},");
        w.Close(";");
        w.Close();
        w.Line();
        w.Line("/// <inheritdoc />");
        w.Open($"public override {e} CreateRow({cur} current, string? contributorName)");
        w.Open($"var row = new {e}", trailer: "");
        foreach (var slot in m.Slots) w.Line($"{slot.Name} = current.{slot.Name},");
        foreach (var value in m.Values) w.Line($"{value.Name} = current.{value.Name},");
        w.Close(";");
        if (m.Has(ContributionModel.AttributionContributor)) w.Line("row.__sparkContributorName = contributorName;");
        if (m.Has(ContributionModel.AttributionUpdatedAt)) w.Line("row.__sparkUpdatedAt = current.UpdatedAt;");
        if (m.Has(ContributionModel.AttributionHistory)) w.Line("row.__sparkContributionCount = current.ContributionCount;");
        w.Line("return row;");
        w.Close();

        w.Close();
    }

    // ------------------------------------------------------------------ per element

    /// <summary>
    /// The element's partial: the row key (collections) and the attribution properties, unioned over
    /// every declaration that uses the element, so two targets sharing one element type emit it once.
    /// </summary>
    public static string Element(ElementDeclaration element, IReadOnlyList<SlotModel> slots, int attribution)
    {
        var w = new Writer();
        w.Raw(Header);
        var ns = !string.IsNullOrEmpty(element.Namespace);
        if (ns) w.Open($"namespace {element.Namespace}");
        foreach (var container in element.ContainingDeclarations)
            w.Open(container);
        w.Open(element.Declaration);

        var first = true;
        void Gap() { if (!first) w.Line(); first = false; }

        if (slots.Count > 0)
        {
            Gap();
            w.Line("/// <summary>");
            w.Line($"/// The row key: the slot tuple (<c>{string.Join("/", slots.Select(s => "{" + s.Name + "}"))}</c>), formatted culture-independently.");
            w.Line("/// Deterministic and get-only, so an existing row keeps its identity across loads and saves.");
            w.Line("/// Generated by MintPlayer.Spark.Contributions.");
            w.Line("/// </summary>");
            w.Line("[global::MintPlayer.Spark.Abstractions.ValueKey]");
            w.Line($"public string Key => {SlotKeyExpression(slots, "this")};");
        }

        if ((attribution & ContributionModel.AttributionContributor) != 0)
        {
            Gap();
            w.Line("internal string? __sparkContributorName;");
            w.Line();
            w.Line("/// <summary>Who wrote the current version (read-only; rendering hint <c>contributionAttribution</c>). Resolved at read time, never stored.</summary>");
            w.Line("public string? ContributorName => __sparkContributorName;");
        }
        if ((attribution & ContributionModel.AttributionUpdatedAt) != 0)
        {
            Gap();
            w.Line("internal global::System.DateTime? __sparkUpdatedAt;");
            w.Line();
            w.Line("/// <summary>When the current version was written, in UTC (read-only; rendering hint <c>contributionAttribution</c>).</summary>");
            w.Line("public global::System.DateTime? UpdatedAt => __sparkUpdatedAt;");
        }
        if ((attribution & ContributionModel.AttributionHistory) != 0)
        {
            Gap();
            w.Line("internal int? __sparkContributionCount;");
            w.Line();
            w.Line("/// <summary>How many contributions the slot has (read-only; rendering hint <c>contributionAttribution</c>).</summary>");
            w.Line("public int? ContributionCount => __sparkContributionCount;");
        }

        w.Close();
        foreach (var _ in element.ContainingDeclarations)
            w.Close();
        if (ns) w.Close();
        return w.ToString();
    }

    // ------------------------------------------------------------------ per assembly

    public static string Registration(string rootNamespace, IReadOnlyList<ContributionModel> models)
    {
        var w = new Writer();
        w.Raw(Header);
        w.Open($"namespace {rootNamespace}");
        w.Line("/// <summary>");
        w.Line("/// Registers this assembly's contribution declarations and their element row keys when the assembly loads.");
        w.Line("/// <c>AddContributions()</c> reads <see cref=\"global::MintPlayer.Spark.Contributions.ContributionRegistry\"/>; nothing is scanned.");
        w.Line("/// </summary>");
        w.Open("internal static class SparkContributionsRegistration");
        w.Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        w.Open("internal static void Register()");
        foreach (var element in models.Where(m => m.IsCollection).Select(m => m.Element.FullyQualified).Distinct().OrderBy(x => x, StringComparer.Ordinal))
        {
            w.Line("global::MintPlayer.Spark.Abstractions.Model.SparkValueObjects.Register(" +
                   $"typeof({element}), \"Key\", static o => (({element})o).Key);");
        }
        foreach (var model in models)
            w.Line($"global::MintPlayer.Spark.Contributions.ContributionRegistry.Register({model.MetadataType}.Instance);");
        w.Close();
        w.Close();
        w.Close();
        return w.ToString();
    }

    // ------------------------------------------------------------------ helpers

    private static string SlotPath(ContributionModel m) => string.Concat(m.Slots.Select(s => "{" + s.Name + "}/"));

    /// <summary><c> + Format(a) + "/" + Format(b)</c>; empty without slots.</summary>
    private static string SlotConcat(ContributionModel m, Func<SlotModel, string> expression)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < m.Slots.Length; i++)
        {
            if (i > 0) sb.Append(" + \"/\"");
            sb.Append(" + ").Append(m.Slots[i].Format(expression(m.Slots[i])));
        }
        return sb.ToString();
    }

    /// <summary>The user segment after the slots: <c>"/User/"</c>, or <c>"User/"</c> straight after the prefix's slash when there are none.</summary>
    private static string UserSegment(ContributionModel m) => m.Slots.Length > 0 ? " + \"/User/\"" : " + \"User/\"";

    private static string SlotKeyExpression(ContributionModel m, string owner) => SlotKeyExpression(m.Slots.ToList(), owner);

    private static string SlotKeyExpression(IReadOnlyList<SlotModel> slots, string owner)
        => slots.Count == 0
            ? "\"\""
            : string.Join(" + \"/\" + ", slots.Select(s => s.Format($"{owner}.{s.Name}")));

    private static string StringArray(IEnumerable<string> items)
    {
        var list = items.ToList();
        return list.Count == 0
            ? "global::System.Array.Empty<string>()"
            : "new string[] { " + string.Join(", ", list.Select(i => "\"" + i + "\"")) + " }";
    }

    private static IEnumerable<string> AttributionNames(int attribution)
    {
        if ((attribution & ContributionModel.AttributionContributor) != 0) yield return "ContributorName";
        if ((attribution & ContributionModel.AttributionUpdatedAt) != 0) yield return "UpdatedAt";
        if ((attribution & ContributionModel.AttributionHistory) != 0) yield return "ContributionCount";
    }

    private static string AttributionExpression(int attribution)
    {
        const string type = "global::MintPlayer.Spark.Contributions.ContributionAttribution";
        var parts = new List<string>();
        if ((attribution & ContributionModel.AttributionContributor) != 0) parts.Add(type + ".Contributor");
        if ((attribution & ContributionModel.AttributionUpdatedAt) != 0) parts.Add(type + ".UpdatedAt");
        if ((attribution & ContributionModel.AttributionHistory) != 0) parts.Add(type + ".History");
        return parts.Count == 0 ? type + ".None" : string.Join(" | ", parts);
    }

    /// <summary>A minimal indented writer with <c>\n</c> line endings, so snapshots don't depend on the OS.</summary>
    private sealed class Writer
    {
        private readonly StringBuilder sb = new();
        private readonly Stack<string> trailers = new();
        private int indent;

        public void Raw(string text) => sb.Append(text).Append('\n');

        public void Line(string text = "")
        {
            if (text.Length > 0)
                sb.Append(' ', indent * 4).Append(text);
            sb.Append('\n');
        }

        public void Open(string header, string trailer = "")
        {
            Line(header);
            Line("{");
            indent++;
            trailers.Push(trailer);
        }

        public void Close(string? suffix = null)
        {
            indent--;
            var trailer = trailers.Pop();
            Line("}" + (suffix ?? trailer));
        }

        public override string ToString() => sb.ToString();
    }
}
