// Generated by MintPlayer.Spark.Authorization
// This file was generated once and will NOT be overwritten.
// Feel free to customize it to match your application's needs.

import {
  provideSparkAuth,
  withSparkAuth,
  sparkAuthRoutes,
  sparkAuthGuard,
  SparkAuthBarComponent,
  SparkAuthService,
} from '@mintplayer/ng-spark-auth';

import type { SparkAuthConfig, SparkAuthRouteConfig } from '@mintplayer/ng-spark-auth';

/**
 * Provides Spark authentication services.
 *
 * Add to your `app.config.ts` providers array:
 * ```typescript
 * import { setupSparkAuthProviders, setupSparkAuthHttp } from './spark-auth.setup';
 *
 * export const appConfig: ApplicationConfig = {
 *   providers: [
 *     provideHttpClient(setupSparkAuthHttp()),
 *     ...setupSparkAuthProviders(),
 *   ]
 * };
 * ```
 */
export function setupSparkAuthProviders(config?: Partial<SparkAuthConfig>) {
  return [provideSparkAuth(config)];
}

/**
 * Returns an HttpFeature that attaches the Spark auth interceptor.
 *
 * Usage: `provideHttpClient(setupSparkAuthHttp())`
 */
export function setupSparkAuthHttp() {
  return withSparkAuth();
}

/**
 * Returns routes for authentication pages (login, register, forgot-password, etc.).
 *
 * Add to your `app.routes.ts`:
 * ```typescript
 * import { setupSparkAuthRoutes } from './spark-auth.setup';
 *
 * export const routes: Routes = [
 *   {
 *     path: '',
 *     children: [
 *       ...setupSparkAuthRoutes(),
 *       // ... your other routes
 *     ]
 *   }
 * ];
 * ```
 */
export function setupSparkAuthRoutes(config?: SparkAuthRouteConfig) {
  return sparkAuthRoutes(config);
}

/** Re-export the auth guard for protecting routes. */
export { sparkAuthGuard };

/** Re-export the auth bar component for use in templates. */
export { SparkAuthBarComponent };

/** Re-export the auth service for programmatic auth operations. */
export { SparkAuthService };

/** Re-export config types for customization. */
export type { SparkAuthConfig, SparkAuthRouteConfig };
